terrakube-io/terrakube

- .github/workflows/maven-settings.xml
- .github/workflows/pull_request.yml
- .github/workflows/release.yml
resolves #15  
Including 2 workflows:
1. Validate that code compiles for a new PR
2. Push docker images when a new tag is created
> Include github actions to PRs and  new releases

- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-1.1.xml
Add constraints for:
- Organization
- Module
- Workspace
- Variables
- Secrets
- Environment Variables
> Validations

- openapi-spec/v1_2.yml
> Add open api specification for v1.2

- README.md
- api-job/pom.xml
- api-registry/pom.xml
- pom.xml
> Release 1.3.0

- api-registry/src/main/java/org/azbuilder/registry/service/git/GitServiceImpl.java
- api/src/main/java/org/azbuilder/api/plugin/security/groups/azure/AzureAdGroupServiceImpl.java
- api/src/main/java/org/azbuilder/api/plugin/security/user/azure/AzureAuthenticatedUserImpl.java
- api/src/main/java/org/azbuilder/api/plugin/vcs/TokenService.java
- api/src/main/java/org/azbuilder/api/plugin/vcs/provider/azdevops/AzDevOpsToken.java
- api/src/main/java/org/azbuilder/api/plugin/vcs/provider/azdevops/AzDevOpsTokenService.java
- api/src/main/java/org/azbuilder/api/plugin/vcs/provider/gitlab/GitLabTokenService.java
- api/src/main/java/org/azbuilder/api/rs/module/Module.java
- api/src/main/java/org/azbuilder/api/rs/vcs/VcsType.java
- api/src/main/resources/application.properties
- api/src/main/resources/db/changelog/local/changelog-1.4.xml
- api/src/test/resources/application-test.properties
- pom.xml
- Add support for Azure DevOps private repositories from https://dev.azure.com/
- Fix issue with authentication from Azure AD guest users
> Add support for Azure DevOps private repositories 

- api-job/pom.xml
- api-job/src/main/resources/application.properties
- api-job/src/test/resources/application.properties
- api-registry/pom.xml
- api-registry/src/main/java/org/azbuilder/registry/service/module/ModuleServiceImpl.java
- api-registry/src/main/java/org/azbuilder/registry/service/provider/ProviderServiceImpl.java
- api-registry/src/main/resources/application.properties
- api-registry/src/test/resources/application-test.properties
- pom.xml
Upgrade terrakube client to 0.7.1
> Release 1.5.1

- api-job/pom.xml
- api-job/src/main/java/org/azbuilder/api/schedule/JobService.java
- api-job/src/main/java/org/azbuilder/api/schedule/ScheduleJobService.java
- api-registry/pom.xml
- api-registry/src/main/java/org/azbuilder/registry/controller/ModuleWebServiceImpl.java
- api-registry/src/main/java/org/azbuilder/registry/controller/ReadMeWebServiceImpl.java
- api-registry/src/main/java/org/azbuilder/registry/service/module/ModuleService.java
- api-registry/src/main/java/org/azbuilder/registry/service/module/ModuleServiceImpl.java
- api/src/main/java/org/azbuilder/api/rs/checks/job/TeamApproveJob.java
- api/src/main/java/org/azbuilder/api/rs/module/Module.java
- api/src/main/resources/db/changelog/local/changelog-1.6.xml
- api/src/test/java/org/azbuilder/api/ModuleTests.java
- pom.xml
Add support to count module downloads
> Count module downloads

- api/src/main/java/org/azbuilder/api/rs/template/Template.java
- openapi-spec/v1_6.yml
- pom.xml
- postman/AzBuilder v1.6.postman_collection.json
- Adding missing access role Fix #93 
- Adding v1.6 postman and OpenApi spec
> Registry issue

- api/pom.xml
- api/src/main/java/org/azbuilder/api/plugin/scheduler/ScheduleVcs.java
- api/src/main/java/org/azbuilder/api/plugin/scheduler/ScheduleVcsService.java
- api/src/main/java/org/azbuilder/api/plugin/scheduler/ScheduleWorkspaceService.java
- api/src/main/java/org/azbuilder/api/plugin/security/audit/azure/AzureAuditorAwareImpl.java
- api/src/main/java/org/azbuilder/api/plugin/vcs/TokenService.java
- api/src/main/java/org/azbuilder/api/rs/hooks/module/ModuleReadTokenHook.java
- api/src/main/java/org/azbuilder/api/rs/hooks/vcs/VcsReadTokenHook.java
- api/src/main/java/org/azbuilder/api/rs/module/Module.java
- api/src/main/java/org/azbuilder/api/rs/vcs/Vcs.java
- pom.xml
> Update to Elide 6.0 and refactor refresh token logic

- api/pom.xml
- pom.xml
Upgrade azure-spring-boot-bom to 3.10.2
> Upgrade azure dependency

- api/src/main/java/org/azbuilder/api/rs/module/Module.java
- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-1.8.xml
- api/src/test/java/org/azbuilder/api/ModuleTests.java
- pom.xml
Adding createdBy, createdDate, updatedBy and updatedDate for modules
> Module Audit Fields

- api/src/main/java/org/azbuilder/api/plugin/cors/CorsConfiguration.java
- api/src/main/resources/application.properties
- pom.xml
There are some kubernetes ingress that does not support CORS, we need to handel this from the backend api.
Added new value in application.properties:
org.terrakube.ui.url
> Fix CORS issue API

- pom.xml
> spring2.6.8

- .github/workflows/pull_request_ui.yml
- .github/workflows/release.yml
> Adding Github Actions for UI

- README.md
> Fix gitpod url [skip ci]

- ui/src/domain/Settings/SSHKeys.jsx
> fix SSH keys in UI

- api/src/main/java/org/terrakube/api/plugin/scheduler/ScheduleJobService.java
- api/src/main/java/org/terrakube/api/rs/hooks/job/JobManageHook.java
- executor/src/main/java/org/terrakube/executor/service/scripts/ScriptEngineService.java
- executor/src/main/java/org/terrakube/executor/service/scripts/bash/BashEngine.java
- executor/src/main/java/org/terrakube/executor/service/terraform/TerraformExecutorServiceImpl.java
Correctly handle bash scripts errors in job executions
> Improve error handling for bash scripts in Jobs

- executor/pom.xml
This will fix some compilation issues with Terrakube extensions and java 17 in Gitpod
> Update groovy to 3.0.12

- .github/workflows/release.yml
Update external dependencies in executor adding tools jq and curl.
> Update external dependencies for Executor

- ui/src/domain/Workspaces/Details.jsx
> Fixes jobs order in workspaces

- ui/src/config/axiosConfig.js
- ui/src/domain/Home/App.js
- ui/src/domain/Home/ProfilePicture.jsx
- ui/src/domain/UserSettings/Tokens.jsx
- ui/src/domain/UserSettings/UserSettings.css
- ui/src/domain/UserSettings/UserSettings.jsx
New page to manage user Tokens in User Settings
Create a new Token
> Including PAT in User Settings 

- api/src/main/java/org/terrakube/api/plugin/manage/OrganizationManageService.java
- api/src/main/java/org/terrakube/api/rs/Organization.java
- api/src/main/java/org/terrakube/api/rs/hooks/organization/OrganizationManageHook.java
When creating a new organization by default the following templates will be created inside the organization:
- Terraform-Plan
- Terraform-Plan/Apply
- Terraform-Destroy
Fixes #236
> Adding default template in organizations

- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorService.java
> Improve log output adding TF_IN_AUTOMATION env variable

- api/src/main/java/org/terrakube/api/plugin/softdelete/SoftDeleteService.java
- api/src/main/java/org/terrakube/api/rs/hooks/workspace/WorkspaceManageHook.java
- api/src/main/java/org/terrakube/api/rs/workspace/Workspace.java
- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.9.0-delete-workspace.xml
- thunder-tests/thunderclient.json
- ui/src/domain/Workspaces/Details.jsx
Adding option to soft delete a workspace from the UI and disable all the shedule triggers.
> Soft Delete wokspace UI/API

- api/src/main/java/org/terrakube/api/plugin/softdelete/SoftDeleteService.java
- api/src/main/java/org/terrakube/api/rs/Organization.java
- api/src/main/java/org/terrakube/api/rs/hooks/organization/OrganizationManageHook.java
- api/src/main/java/org/terrakube/api/rs/hooks/workspace/WorkspaceManageHook.java
- api/src/main/java/org/terrakube/api/rs/module/Module.java
- ui/src/domain/Settings/General.jsx
Adding soft delete organization logic, this will also mark workspaces as deleted and disable the schedule triggers.
> Soft delete organization

- ui/src/domain/Settings/VCS.jsx
> Fix wrong callback url vcs logic

- ui/src/domain/Settings/GlobalVariables.jsx
- ui/src/domain/Settings/Settings.jsx
> Adding global variables to Organization Settings

- .gitpod.yml
- ui/src/domain/Home/App.js
- ui/src/domain/Organizations/Details.jsx
- ui/src/domain/Settings/AddTemplate.jsx
- ui/src/domain/Workspaces/Create.jsx
- ui/src/domain/Workspaces/Details.jsx
- ui/src/domain/Workspaces/Workspaces.css
> Adding CLI and API Driven workflows to workspaces

- api/src/main/java/org/terrakube/api/plugin/scheduler/ScheduleJob.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/TclService.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/model/Flow.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/model/FlowType.java
This will improve the error handling when using an invalid template when using the jobs
> Improved error handling for invalid templates

- ui/package.json
- ui/src/domain/Jobs/Details.jsx
- ui/src/domain/Workspaces/Details.jsx
- ui/yarn.lock
fixes #307 
Adding support to use UI templates. Docs: https://docs.terrakube.org/user-guide/organizations/templates/ui-templates
> Adding ui templates support in workspaces

- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorService.java
Adding some extra env variables when sending the executor job, this are usefull for notifications
> Adding workspace and organization name in job as env var

- ui/src/domain/Workspaces/Schedules.jsx
> Removing CLI templates from schedules

- ui/Dockerfile
- ui/README.md
- ui/docker-compose.yml
This reverts commit 1ea09c7b0c236d3de0a6b6e8220ebc8a6280a3ef.
> Revert "Simplify Dockerfile UI using bitnami/nginx (#332)"

- ui/package.json
- ui/src/domain/Settings/AddVCS.jsx
- ui/src/domain/Settings/VCS.jsx
- ui/yarn.lock
fixes #81 
Documentation was updated
> Improving callback url in VCS settings

- executor/src/main/java/org/terrakube/executor/plugin/tfstate/local/LocalTerraformStateImpl.java
- ui/src/domain/Workspaces/Details.jsx
- ui/src/domain/Workspaces/States.jsx
> Fix order state in Workspaces

- api/src/main/java/org/terrakube/api/plugin/scheduler/ScheduleJob.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorService.java
- api/src/main/java/org/terrakube/api/repository/StepRepository.java
Adding some internal validation if the executor is down for some reason.
> Check if executor is down

- api/src/main/java/org/terrakube/api/plugin/context/ContextController.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/ScheduleJob.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/ScheduleJobService.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/ScheduleJobTrigger.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/ScheduleVcs.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/TclService.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/model/Flow.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/model/FlowType.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/model/ScheduleTemplate.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/migrate/MigrateJobs.java
- api/src/main/java/org/terrakube/api/plugin/vcs/TokenService.java
Adding support to create schedules inside the templates.
This is usefull for example when we deploy some infrastructure and we need to set some schedule to destroy de infrasctructure or resize it.
We define a job template that creates the infrasctucture using some small size and create two schedule at the end of the template.
Define the size as global variables.
```
flow:
- type: "customScripts"
step: 100
inputsTerraform:
SIZE: $SIZE_SMALL
commands:
- runtime: "BASH"
priority: 100
before: true
script: |
echo "SIZE : $SIZE"
- type: "scheduleTemplates"
step: 200
templates:
- name: "schedule1"
schedule: "0 0/5 * ? * * *"
- name: "schedule2"
schedule: "0 0/10 * ? * * *"
```
Inject the new size using global terraform variables
```
flow:
- type: "customScripts"
step: 100
inputsTerraform:
SIZE: …
```
> Add support to schedule templates inside a job 

- ui/src/domain/Organizations/Details.jsx
- ui/src/domain/Workspaces/Workspaces.css
> Adding search options to Workspaces

- ui/src/domain/Jobs/Details.jsx
> Fix context API request in docker 

- api/src/main/java/org/terrakube/api/plugin/vcs/TokenService.java
- api/src/main/java/org/terrakube/api/plugin/vcs/controller/CallbackController.java
- api/src/main/java/org/terrakube/api/rs/vcs/Vcs.java
- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.14.0-vcs-redirect-url.xml
- ui/src/domain/Settings/AddVCS.jsx
fixes #337 
Documentation updated
> Redirect user to UI once VCS  is completed

- ui/src/domain/Modules/Create.jsx
- ui/src/domain/Organizations/Create.jsx
- ui/src/domain/Settings/AddTemplate.jsx
- ui/src/domain/Settings/AddVCS.jsx
- ui/src/domain/Workspaces/Create.jsx
fixes #399 
Including UI error messages for Authorization errors in Modules, Organizations, Workspaces, VCS and Templates .
Example:
> Adding UI error message for Authorization errors

- api/src/main/java/org/terrakube/api/rs/Organization.java
- api/src/main/java/org/terrakube/api/rs/tag/Tag.java
- api/src/main/java/org/terrakube/api/rs/workspace/Workspace.java
- api/src/main/java/org/terrakube/api/rs/workspace/tag/WorkspaceTag.java
- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.14.0-tags.xml
- ui/src/domain/Settings/Settings.jsx
- ui/src/domain/Settings/Tags.jsx
- ui/src/domain/Workspaces/CLIDriven.jsx
- ui/src/domain/Workspaces/Details.jsx
- ui/src/domain/Workspaces/Tags.jsx
- ui/src/domain/Workspaces/Variables.jsx
> Adding tags supports in workspaces

- api/src/main/resources/db/changelog/local/changelog-2.14.0-tags.xml
- ui/src/domain/Workspaces/Details.jsx
> Adding latest run into workspace overview

- api/pom.xml
- api/src/main/java/org/terrakube/api/plugin/scheduler/ScheduleJob.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorContext.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorService.java
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeController.java
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
- api/src/main/java/org/terrakube/api/plugin/streaming/StreamingService.java
- api/src/main/java/org/terrakube/api/rs/job/JobStatus.java
- executor/src/main/java/org/terrakube/executor/service/logs/LogsService.java
- executor/src/main/java/org/terrakube/executor/service/mode/TerraformJob.java
- executor/src/main/java/org/terrakube/executor/service/status/UpdateJobStatusImpl.java
- executor/src/main/java/org/terrakube/executor/service/terraform/TerraformExecutorServiceImpl.java
- pom.xml
Enable log streaming support when using Terraform CLI remote backend or the cloud block.
> Log Streaming Remote Backend/Cloud Block

- api/pom.xml
- api/src/main/java/org/terrakube/api/plugin/streaming/StreamingService.java
- scripts/setupDevelopmentEnvironmentAzure.sh
Remove unused microsoft-graph dependency, fix streaming issue in the UI and fix the script in gitpod to test azure storage backend adding redis environment variables
> Remove unused microsoft-graph dependency

- ui/src/domain/Modules/List.jsx
> [Feature] Search modules implementation

- ui/src/domain/Workspaces/Details.jsx
> Fix issue UI refreshes to overview for CLI and API Workspaces

- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
- docker-compose/docker-compose.yaml
> Update docker-compose 2.15.0

- README.md
Adding information about Terrakube and the new Terraform BSL license
> Terraform BSL License [skip ci]

- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
- pom.xml
Refactor logic to update workspace tags to fix database constraint const_tag_org issue
Fixes #473
> Refactor logic to update tags

- .gitpod.yml
Hardcode thunder client version 2.6.1 in gitpod so it does not require a subscription
> Gitpod Thunder Client Version

- api/src/main/java/org/terrakube/api/plugin/datasource/DataSourceAutoConfiguration.java
- api/src/main/java/org/terrakube/api/plugin/datasource/DataSourceConfigurationProperties.java
- api/src/main/resources/application-demo.properties
- api/src/main/resources/application.properties
Added possibility to set up the port.  The feature is not tested, can you explain me how to test / reproduce it in the app?
> added mysql port configuration #481

- ui/src/config/axiosConfig.js
- ui/src/domain/Organizations/Details.jsx
- ui/src/domain/Workspaces/Tags.jsx
fixes #478 
Adding:
- Option to filter by tag
- Option to filter by description
- Adding tags list in each workspace
> Adding more filters in Workspace list

- docker-compose/docker-compose.yaml
> Fix docker-compose image name

- api/src/main/java/org/terrakube/api/plugin/scheduler/ScheduleVcs.java
- api/src/main/java/org/terrakube/api/plugin/vcs/provider/bitbucket/BitbucketTokenService.java
Improve Bitbucket refresh token logic
> Improve Bitbucket refresh token logic

- ui/src/domain/Workspaces/States.jsx
If for some reason the logic to build the diagram fail, it will show the error in a box and will show the json state file correctly
> Improve Diagram logic in the UI

- README.md
Adding information about the terraform provider for Terrakube
> Terraform Terrakube provider

- api/src/main/java/org/terrakube/api/plugin/storage/azure/AzureStorageTypeServiceImpl.java
Delete module storage data from the registry container in Azure when the module is deleted in the UI.
Before Delete:
After Delete:
Logs Information:
> Delete module data from storage backend (Azure)

- ui/package.json
- ui/src/domain/Settings/EditTeam.jsx
- ui/src/domain/Settings/Settings.jsx
- ui/src/domain/Settings/Teams.jsx
- ui/yarn.lock
fixes #517 
[Documentation](https://docs.terrakube.io/user-guide/organizations/api-tokens#user-api-tokens-1)
> Adding team API tokens support

- api/src/main/java/org/terrakube/api/plugin/token/team/TeamTokenService.java
- api/src/main/java/org/terrakube/api/rs/token/group/Group.java
- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.17.0-team-token-hours.xml
- ui/src/domain/Settings/EditTeam.jsx
> Adding minutes and hours to Team API generation

- ui/src/domain/Modules/Details.jsx
fixes #472
submodules drowpdownlist
submodule view
submodule switch
submodule source details
> Adding submodules in Module details

- ui/src/domain/Workspaces/CLIDriven.jsx
- ui/src/domain/Workspaces/Details.jsx
> Fix cli driven workspaces view

- api/src/main/java/org/terrakube/api/rs/workspace/history/History.java
- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.17.0-fix-state-archive.xml
- executor/pom.xml
- executor/src/main/java/org/terrakube/executor/plugin/tfstate/aws/AwsTerraformStateImpl.java
- executor/src/main/java/org/terrakube/executor/plugin/tfstate/azure/AzureTerraformStateImpl.java
- executor/src/main/java/org/terrakube/executor/plugin/tfstate/gcp/GcpTerraformStateImpl.java
- executor/src/main/java/org/terrakube/executor/plugin/tfstate/local/LocalTerraformStateImpl.java
This will fix some issues with the default data with the history endpoint with the new fields serial, md5 and lineage
> Fix history entity

- api/pom.xml
- executor/src/main/java/org/terrakube/executor/plugin/tfstate/TerraformState.java
- executor/src/main/java/org/terrakube/executor/plugin/tfstate/aws/AwsTerraformStateImpl.java
- executor/src/main/java/org/terrakube/executor/plugin/tfstate/azure/AzureTerraformStateImpl.java
- executor/src/main/java/org/terrakube/executor/plugin/tfstate/gcp/GcpTerraformStateImpl.java
- executor/src/main/java/org/terrakube/executor/plugin/tfstate/local/LocalTerraformStateImpl.java
- executor/src/main/java/org/terrakube/executor/service/terraform/TerraformExecutorServiceImpl.java
> Fix terraform 1.6.X with MINIO storage backend

- ui/src/domain/Workspaces/Details.jsx
Fix issue to show the child module resources and the correct resource count.
Fix #571
> Fix child module data in workspace details page

- api/src/main/java/org/terrakube/api/plugin/security/audit/dex/DexAuditorAwareImpl.java
- api/src/main/java/org/terrakube/api/plugin/security/authentication/dex/DexWebSecurityAdapter.java
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
- api/src/main/java/org/terrakube/api/plugin/vcs/WebhookResult.java
- api/src/main/java/org/terrakube/api/plugin/vcs/WebhookService.java
- api/src/main/java/org/terrakube/api/plugin/vcs/controller/WebHookController.java
- api/src/main/java/org/terrakube/api/plugin/vcs/provider/github/GitHubWebhookService.java
- api/src/main/java/org/terrakube/api/repository/WebhookRepository.java
- api/src/main/java/org/terrakube/api/rs/hooks/workspace/WorkspaceManageHook.java
- api/src/main/java/org/terrakube/api/rs/job/Job.java
- api/src/main/java/org/terrakube/api/rs/webhook/Webhook.java
- api/src/main/java/org/terrakube/api/rs/webhook/WebhookType.java
- api/src/main/java/org/terrakube/api/rs/workspace/Workspace.java
- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.18.0-webhooks.xml
- ui/src/domain/Jobs/Create.jsx
- ui/src/domain/Jobs/Details.jsx
- ui/src/domain/Workspaces/Details.jsx
When a new push is created in the branch specified in the workspace this will trigger a new Plan and apply job
Adding the via field to show the trigger of the job (UI, CLI, Github, etc)
fixes #36
> Adding webhooks for push when using VCS Github type 

- api/src/main/java/org/terrakube/api/plugin/vcs/WebhookService.java
- api/src/main/java/org/terrakube/api/plugin/vcs/provider/github/GitHubWebhookService.java
- api/src/main/java/org/terrakube/api/plugin/vcs/provider/gitlab/GitLabWebhookService.java
> Adding webhooks for push when using VCS Gitlab type 

- api/src/main/java/org/terrakube/api/plugin/security/audit/dex/DexAuditorAwareImpl.java
Fix small reliability issue in sonar cloud
> Fix small Sonar Cloud Issue

- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeController.java
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
Fix logic to discard jobs when using the CLI driven workflow
> Fix CLI driven workflow discard logic

- .vscode/launch.json
- api/src/main/java/org/terrakube/api/plugin/security/audit/dex/DexAuditorAwareImpl.java
- api/src/main/java/org/terrakube/api/plugin/vcs/WebhookServiceBase.java
- api/src/main/java/org/terrakube/api/plugin/vcs/provider/bitbucket/BitBucketWebhookService.java
- api/src/main/java/org/terrakube/api/plugin/vcs/provider/github/GitHubWebhookService.java
- api/src/main/java/org/terrakube/api/plugin/vcs/provider/gitlab/GitLabWebhookService.java
- api/src/main/java/org/terrakube/api/rs/vcs/Vcs.java
- api/src/main/resources/db/changelog/local/changelog-2.18.0-vcs-custom-endpoint.xml
- ui/src/domain/Settings/AddVCS.jsx
- ui/src/domain/Settings/VCS.jsx
- ui/src/domain/Workspaces/Create.jsx
- ui/yarn.lock
> Adding support to Webhooks for Self hosted VCS providers

- api/src/main/java/org/terrakube/api/plugin/redirect/RedirectController.java
- api/src/main/java/org/terrakube/api/plugin/security/authentication/dex/DexWebSecurityAdapter.java
Adding logic to create a redirect for the following link to the UI.
Some logic will have to be added in React but at least for now it will redirect to the UI and wont return 404
Partial fix for #511
> CLI driven workflow redirect URL

- ui/src/domain/Settings/AddVCS.jsx
- ui/src/domain/Workspaces/Create.jsx
Docs: https://docs.terrakube.io/user-guide/vcs-providers/gitlab-ee-and-ce
> Gitlab EE and CE vcs webhooks

- ui/src/domain/Workspaces/Details.jsx
> Adding workspace unlock/lock button

- ui/src/domain/Workspaces/NodeResource.jsx
- ui/src/domain/Workspaces/States.jsx
> Adding option to see values from state diagram

- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorService.java
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
- api/src/main/java/org/terrakube/api/rs/job/Job.java
- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.19.0-override-vcs.xml
This PR will allow to run a terraform plan using cli-driven workflow in a workspace that is using a VCS connection
Fix #596 
Example:
Workspace using a private VCS connection:
Trigger job from the UI using the VCS connection:
Running a plan using the CLI-driven workflow:
```shell
user@pop-os:~/git/simple-terraform$ terraform plan
Running plan in Terraform Cloud. Output will stream here. Pressing Ctrl-C
will stop streaming the logs, but will not stop the plan running remotely.
Preparing the remote plan...
To view this run in a browser, visit:
https://8080-azbuilder-terrakube-qpd4p8gfjxi.ws-us107.gitpod.io/app/simple/simple-terraform/runs/2
Waiting for the plan to start...
***************************************
Running Terraform PLAN
*************************************** …
```
> Use cli-driven workflow to run plan in VCS workspace

- api/src/main/resources/db/changelog/demo-data/aws.xml
- api/src/main/resources/db/changelog/demo-data/gcp.xml
- api/src/main/resources/db/changelog/demo-data/simple.xml
- ui/src/domain/Organizations/Details.jsx
- ui/src/domain/Workspaces/Tags.jsx
> Save workspace search until cleared

- ui/src/config/authConfig.js
- ui/src/config/authUser.js
https://github.com/AzBuilder/terrakube/issues/664
> feat: migrating oidc.user token information from sessionstorage to localstorage

- .github/workflows/pull_request.yml
- .github/workflows/pull_request_ui.yml
- .github/workflows/release.yml
> Fix github actions versions

- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorService.java
- api/src/main/java/org/terrakube/api/rs/workspace/Workspace.java
- api/src/main/resources/db/changelog/changelog-demo.xml
- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/demo-data/demo-tofu-refactor.xml
- api/src/main/resources/db/changelog/demo-data/demo-tofu.xml
- api/src/main/resources/db/changelog/local/changelog-2.19.0-workspace-tofu-refactor.xml
- ui/src/domain/Workspaces/Details.jsx
Select the IaC type using a dropdown menu like this:
> This could be useful if in the future we would like to add other tools.
> Select IaC type in a dropdown

- api/pom.xml
- api/src/main/java/org/terrakube/api/plugin/vcs/WebhookService.java
- api/src/main/java/org/terrakube/api/repository/WebhookRepository.java
- api/src/main/java/org/terrakube/api/rs/hooks/workspace/WorkspaceManageHook.java
- api/src/main/java/org/terrakube/api/rs/workspace/Workspace.java
- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.19.0-workspace-default-template.xml
- executor/pom.xml
- registry/pom.xml
- ui/src/domain/Workspaces/Create.jsx
- ui/src/domain/Workspaces/Details.jsx
Allow to select which template should be executed when creating a private VCS workspace when doing the git push
Allow to update the template that will be executed when doing a git push
Fix #656
> Allow to create workspace and set default template when doing a git push

- api/src/main/java/org/terrakube/api/plugin/json/TofuJsonController.java
- ui/src/domain/Organizations/Details.jsx
- ui/src/domain/Workspaces/Create.jsx
- ui/src/domain/Workspaces/Details.jsx
> Adding OpenTofu versions in dropdown menu

- api/src/main/java/org/terrakube/api/plugin/security/authentication/dex/DexAuthenticationManagerResolver.java
- api/src/main/java/org/terrakube/api/plugin/security/authentication/dex/DexWebSecurityAdapter.java
- api/src/main/java/org/terrakube/api/plugin/token/pat/PatController.java
- api/src/main/java/org/terrakube/api/plugin/token/pat/PatService.java
- api/src/main/java/org/terrakube/api/plugin/token/team/TeamTokenController.java
- api/src/main/java/org/terrakube/api/plugin/token/team/TeamTokenService.java
- api/src/main/java/org/terrakube/api/rs/token/group/Group.java
- api/src/main/java/org/terrakube/api/rs/token/pat/Pat.java
- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.19.0-token-expiration.xml
- thunder-tests/thunderclient.json
Allow to revoke PAT ot Team Token.
```
DELETE {{terrakubeApi}}/pat/v1/{tokenId}
```
```
DELETE {{terrakubeApi}}/access-token/v1/teams/3214b236-e52f-4233-958f-32d23292f891
```
Once a token has been revoke, the API will return 401
> Allow to revoke a Pat/Team Token

- api/src/main/java/org/terrakube/api/plugin/datasource/DataSourceAutoConfiguration.java
- api/src/main/java/org/terrakube/api/plugin/datasource/DataSourceConfigurationProperties.java
- api/src/main/resources/application-demo.properties
- api/src/main/resources/application.properties
> allow customization of port and schema for postgres dbs

- api/src/main/java/org/terrakube/api/plugin/streaming/StreamingConfiguration.java
- api/src/main/java/org/terrakube/api/plugin/streaming/StreamingProperties.java
- api/src/main/java/org/terrakube/api/rs/module/GitTagsCache.java
- api/src/main/java/org/terrakube/api/rs/module/Module.java
- api/src/main/resources/application-demo.properties
- api/src/main/resources/application.properties
- api/src/test/resources/application-test.properties
- executor/src/main/java/org/terrakube/executor/configuration/RedisAutoConfiguration.java
- executor/src/main/java/org/terrakube/executor/configuration/RedisProperties.java
- executor/src/main/resources/application.properties
- scripts/setupDevelopmentEnvironment.sh
- scripts/setupDevelopmentEnvironmentAzure.sh
- scripts/setupDevelopmentEnvironmentGcp.sh
- scripts/setupDevelopmentEnvironmentMinio.sh
This PR
- add user parameter and possibility to use SSL server with Redis
- changes liquibase defaultSchema parameter to use DatasourceSchema as does the PostgreSQL datasource
> Redis SSL improvement (+postgres fix)

- ui/src/domain/Workspaces/Details.jsx
This PR will improve the way that terrakube is parsing the state for nested child modules
Fix #711
> Improve logic to handle child_modules in the UI

- api/src/main/java/org/terrakube/api/plugin/importer/tfcloud/services/WorkspaceService.java
> Fix Importer for workspaces without state

- api/src/main/java/org/terrakube/api/plugin/importer/tfcloud/WorkspaceImport.java
- api/src/main/java/org/terrakube/api/plugin/importer/tfcloud/WorkspaceImportRequest.java
- api/src/main/java/org/terrakube/api/plugin/importer/tfcloud/services/WorkspaceService.java
- ui/src/domain/Workspaces/Import.jsx
> Adding executionMode to Workspace Importer

- api/src/main/java/org/terrakube/api/plugin/importer/tfcloud/TagResponse.java
- api/src/main/java/org/terrakube/api/plugin/importer/tfcloud/services/WorkspaceService.java
- api/src/main/java/org/terrakube/api/rs/tag/Tag.java
> Add support to import tags in Workspaces importer

- api/src/main/java/org/terrakube/api/plugin/importer/tfcloud/controller/TfCloudController.java
- api/src/main/java/org/terrakube/api/plugin/importer/tfcloud/services/WorkspaceService.java
- ui/src/domain/Workspaces/Import.jsx
> Improving log details for Workspace Importer

- api/src/main/java/org/terrakube/api/plugin/vcs/provider/gitlab/GitLabWebhookService.java
> Adding support to Gitlab Webhooks VCS subgroups

- .github/workflows/release.yml
- scripts/setupDevelopmentEnvironment.sh
- scripts/setupDevelopmentEnvironmentAzure.sh
- scripts/setupDevelopmentEnvironmentChe.sh
- scripts/setupDevelopmentEnvironmentGcp.sh
- scripts/setupDevelopmentEnvironmentMinio.sh
- ui/Dockerfile
- ui/src/domain/Home/App.js
> Added Terrakube Version Number in UI

- ui/src/domain/Settings/EditTeam.jsx
- ui/src/domain/UserSettings/Tokens.jsx
fixes #704 
Team API Token
API Token
> Added delete button to Personal and Team API Token

- ui/src/domain/Workspaces/States.jsx
Show the state in correct format in the UI.
> Show state in correct format in the UI

- api/src/main/java/org/terrakube/api/rs/Organization.java
- api/src/main/java/org/terrakube/api/rs/hooks/workspace/WorkspaceManageHook.java
- api/src/main/java/org/terrakube/api/rs/workspace/Workspace.java
- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.20.0-detault-execution-mode.xml
- ui/src/domain/Settings/General.jsx
- ui/src/domain/Workspaces/Create.jsx
> Add the ability to specify a default execution mode at Organization level

- ui/src/domain/Modules/List.jsx
- ui/src/domain/Organizations/Details.jsx
- ui/src/domain/Workspaces/Create.jsx
> Added Module and Workspace Pagination

- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorService.java
- ui/src/domain/Workspaces/Details.jsx
This will add support to select which agent will run the job inside the workspace settings
> Support to select job agent in the UI

- ui/src/domain/Workspaces/States.jsx
> Fixes issue displaying the correct state in tabs

- api/src/main/java/org/terrakube/api/plugin/redirect/RedirectController.java
- ui/src/domain/Home/App.js
- ui/src/domain/Workspaces/Details.jsx
> Redirect to job view when using remote execution

- api/src/main/java/org/terrakube/api/plugin/redirect/RedirectController.java
- ui/src/domain/Home/App.js
- ui/src/domain/Organizations/Details.jsx
- ui/src/domain/Workspaces/Details.jsx
fixes #808 
Added organization to the URL; if no organization is added to the URL, the current organization will be used to avoid breaking changes.
> Added organizationid to url for Workspaces

- ui/package.json
- ui/src/domain/Home/App.css
- ui/src/domain/Home/Home.css
- ui/src/domain/Home/Home.jsx
- ui/src/domain/Home/MainMenu.jsx
- ui/src/domain/Home/ProfilePicture.jsx
- ui/src/domain/Jobs/Create.jsx
- ui/src/domain/Jobs/Details.jsx
- ui/src/domain/Modules/Create.jsx
- ui/src/domain/Modules/Details.jsx
- ui/src/domain/Modules/List.jsx
- ui/src/domain/Organizations/Create.jsx
- ui/src/domain/Organizations/Details.jsx
- ui/src/domain/Settings/EditTeam.jsx
- ui/src/domain/Settings/General.jsx
- ui/src/domain/Settings/GlobalVariables.jsx
- ui/src/domain/Settings/SSHKeys.jsx
- ui/src/domain/Settings/Settings.jsx
- ui/src/domain/Settings/Tags.jsx
- ui/src/domain/UserSettings/Tokens.jsx
- ui/src/domain/UserSettings/UserSettings.jsx
- ui/src/domain/Workspaces/CLIDriven.jsx
- ui/src/domain/Workspaces/Create.jsx
- ui/src/domain/Workspaces/Details.jsx
- ui/src/domain/Workspaces/Import.jsx
- ui/src/domain/Workspaces/Schedules.jsx
- ui/src/domain/Workspaces/Tags.jsx
- ui/src/domain/Workspaces/Variables.jsx
- ui/yarn.lock
- This will slightly change the look and feel, improve performance, and allow the use of new features.
- Added spin to show loading 
fixes #798
> Update Antd to v5

- executor/src/main/java/org/terrakube/executor/service/status/UpdateJobStatusImpl.java
> Added running status for Job Steps

- ui/src/domain/Jobs/Details.jsx
- ui/src/domain/Workspaces/Details.jsx
Fixed an issue introduced during antd migration
> Fixed the format for jobs logs

- api/src/main/java/org/terrakube/api/plugin/scheduler/ScheduleJob.java
> Fix workspace lock for expired jobs

- ui/src/domain/Modules/Create.jsx
> Validate module name length

- dynamic-credential-setup/aws/README.md
- dynamic-credential-setup/aws/datasource.tf
- dynamic-credential-setup/aws/main.tf
- dynamic-credential-setup/aws/output.tf
- dynamic-credential-setup/aws/provider.tf
- dynamic-credential-setup/aws/variables.tf
Adding small terraform code to setup the dynamic credentials in AWS and how to test using a simple workspace in terrakube using the remote CLI driven workflow
> AWS Dynamic Provider Credentials Setup example with Terraform

- dynamic-credential-setup/azure/README.md
- dynamic-credential-setup/azure/datasource.tf
- dynamic-credential-setup/azure/main.tf
- dynamic-credential-setup/azure/provider.tf
- dynamic-credential-setup/azure/variables.tf
Adding small terraform code to setup the dynamic credentials in AWS and how to test using a simple workspace in terrakube using the remote CLI driven workflow
> Azure Dynamic Provider Credentials Setup example with Terraform

- ui/src/domain/Jobs/Create.jsx
This will serve as a visual help to avoid unwanted destroy executions
> enhancement: added different color to destroy button

- api/src/main/java/org/terrakube/api/plugin/scheduler/ScheduleJob.java
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
- api/src/main/java/org/terrakube/api/plugin/vcs/WebhookService.java
- api/src/main/java/org/terrakube/api/rs/job/Job.java
- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.21.0-has-changes.xml
- executor/pom.xml
- executor/src/main/java/org/terrakube/executor/service/status/UpdateJobStatusImpl.java
- ui/src/domain/Organizations/Details.jsx
Job with no changes will be marked as completed as the below image.
> Refactor validation job with no changes

- api/src/main/java/org/terrakube/api/plugin/vcs/WebhookService.java
- ui/src/domain/Workspaces/Details.jsx
This will allow processing of multiple branches using regex matching in the list of branches
> feat: add multiple branch support for VCS

- api/src/main/java/org/terrakube/api/plugin/vcs/WebhookService.java
As per https://github.com/AzBuilder/terrakube/pull/1006
> fix: add override branch on job

- api/src/main/java/org/terrakube/api/plugin/json/TofuJsonController.java
- api/src/main/java/org/terrakube/api/plugin/json/TofuJsonProperties.java
- api/src/main/resources/application-demo.properties
- api/src/main/resources/application.properties
- docker-compose/api.env
- docker-compose/executor.env
- scripts/local/api.env
- scripts/local/executor.env
- scripts/setupDevelopmentEnvironment.sh
- scripts/setupDevelopmentEnvironmentAzure.sh
- scripts/setupDevelopmentEnvironmentChe.sh
- scripts/setupDevelopmentEnvironmentGcp.sh
- scripts/setupDevelopmentEnvironmentMinio.sh
- telemetry-compose/api.env
- telemetry-compose/executor.env
> Allow to configure custom OpenTofu releases URL

- .github/workflows/release.yml
- api/pom.xml
- executor/pom.xml
- registry/pom.xml
- ui/Dockerfile
> feat: added arm64 images support

- api/src/main/java/org/terrakube/api/plugin/vcs/WebhookService.java
- api/src/main/java/org/terrakube/api/repository/TemplateRepository.java
This will fix the webhook creation for a workspace that is using a private connection
> Fix webhook logic creation

- api/src/main/java/org/terrakube/api/plugin/scheduler/ScheduleJob.java
> Missing logic for github status

- api/pom.xml
- executor/pom.xml
- registry/pom.xml
> Update  JVM version

- api/src/main/java/org/terrakube/api/plugin/token/pat/PatService.java
- api/src/main/java/org/terrakube/api/plugin/token/team/TeamTokenService.java
The previous code generates the JWS before saving the token records by then a new key ID is generated, hence causing the ID in the JWT different from what's saved in Terrakube database.
This change addresses this by moving the save operation before the JWS generation and reusing the ID generated by JPA/Spring in the JWT, in an exception, the record in the Terrakube database will be removed.
fixes #1086
> fix: #1086 make JWT jti consistent with what's in system

- executor/src/main/java/org/terrakube/executor/service/workspace/SetupWorkspaceImpl.java
Clone submodules if need it inside the executor workspace setup
Fix #1094
> Clone submodules in executor

- api/pom.xml
Updating the SQL driver and downgrading elide.
There is one issue when running with version 7.1.0 and sql_azure it looks like it is a bug in elide i will have to check in more detail and maybe create an issue with the upstream library
> Update Mssql jdbc

- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
> Fix speculative plan in ssh connected workspaces

- api/pom.xml
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeController.java
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
- executor/src/main/java/org/terrakube/executor/service/status/UpdateJobStatusImpl.java
This contains the following:
- This will fix the issue when trying to calculate the queue position when a workspace was deleted in "waitingForApproval" status
Fix #1122
- Small issue when running with Azure SQL with 5 DTU when trying the do a PATCH operation to the JOB api and the list step is empty
> Fix Calculate run position in queue

- api/src/main/java/org/terrakube/api/rs/hooks/workspace/WorkspaceManageHook.java
* Fix webhook issue with air gapped server
> Fix webhooks for air gapped servers (#1148)

- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
Adding support to run a remote plan and run the apply like the following when using the CLI driven workflow:
```shell
terraform plan -out myPlan.tfplan
terraform apply myPlan.tfplan
```
Fix #1028
> Support to run "terraform apply myPlan.tfplan" for remote CLI driven workflow

- executor/src/main/java/org/terrakube/executor/service/terraform/TerraformExecutorServiceImpl.java
Fix issue [#1268](https://github.com/AzBuilder/terrakube/issues/1268)
> fix: Wrong terraformWorkingDir when user not type path with leading "/" in workspace configuration (#1268)

- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeController.java
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
The Terraform client may ask for re-transmission with offset and limit in the request parameter, the server should implement this feature to avoid truncated logs.
1. Formation
fix #1283
> fix: trucated logs from Terraform CLI

- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
Add missing status for CLI driven workflow queue.
related to https://github.com/AzBuilder/terrakube/pull/1287
> Adding missing status

- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorService.java
This will fix some small issue when calling the executor component after upgrading to spring 3.3.4
> fix: content type issue when using spring 3.3.4

- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/model/Command.java
- executor/src/main/java/org/terrakube/executor/service/mode/Command.java
- executor/src/main/java/org/terrakube/executor/service/scripts/ScriptEngineService.java
Only print the content of the script when verbose is on.
1. import and format added by the editor when saving
> feat: Add verbose mode

- ui/package.json
- ui/src/domain/Settings/Teams.jsx
- ui/yarn.lock
- This will correctly show the team information in the UI
- Adding some missing dependency when running the UI (related to this PR #1320 that was merged yesterday)
Fix #1335
> fix: showing manage state in teams management UI

- api/src/main/java/org/terrakube/api/plugin/vcs/WebhookService.java
When the push event is for changes on the workspace default branch, the job should use the workspace default template.
1. Remove potential null pointer reference
2. format
> fix: Use default template on default branch

- api/pom.xml
fix: https://github.com/AzBuilder/terrakube/issues/1414
> fix: MySQL Connector/J artifacts moved warning

- registry/src/main/java/org/terrakube/registry/configuration/authentication/dex/DexWebSecurityAdapter.java
- registry/src/main/java/org/terrakube/registry/configuration/authentication/local/LocalWebSecurityAdapter.java
fix: https://github.com/AzBuilder/terrakube/issues/1419
> fix: for annotations has been deprecated

- api/pom.xml
- executor/pom.xml
fix https://github.com/AzBuilder/terrakube/issues/1390
> deps: Update Jedis Client from 4.4.8 to version 5.X

- api/pom.xml
- pom.xml
- registry/pom.xml
fix: https://github.com/AzBuilder/terrakube/issues/1417
> fix: problems encountered while building the effective model

- api/pom.xml
- registry/pom.xml
fix: https://github.com/AzBuilder/terrakube/issues/1429
> fix: remove explicit junit-jupiter versioning

- executor/pom.xml
> fix: Terraform download when using arm64

- .github/workflows/release.yml
> fix: Update pipeline to use correct user in ARM image

- ui/src/domain/Settings/EditTeam.jsx
- ui/src/domain/Settings/Teams.jsx
> feat: Allow to change manageCollection permission from the UI

- ui/src/domain/Workspaces/Details.jsx
- ui/src/domain/Workspaces/Variables.jsx
Showing more information in workspace details regarding global variables that will be used
Fix #1526
> feat: Showing global variables in workspace details

- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ephemeral/EphemeralExecutorService.java
Hi @alfespa17 ! 
We would like to use that feature to schedule our jobs on the correct node instance ! Do you think that could benefit to Terrakube users ?
> feat: Allow tolerations for ephemeral agents

- api/pom.xml
- executor/pom.xml
- pom.xml
- registry/pom.xml
This will update the buildpack version used to build the images for the API, Registry and Executor
> deps: Update Buildpacks version

- api/src/main/java/org/terrakube/api/rs/job/Job.java
This is related to #1622, but just fixing one of the topics mentioned there.
> Allow to set 'overrideBranch' for Jobs via API

- api/src/main/java/org/terrakube/api/plugin/token/pat/PatService.java
- api/src/test/java/org/terrakube/api/TokenTests.java
- ui/src/domain/UserSettings/Tokens.jsx
The UI will look like the following:
This will partially fix the following issue #1618
> feat: Allow no expiration personal access token

- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
- api/src/main/java/org/terrakube/api/repository/JobRepository.java
> fix: Add organizationName in query to check running jobs  and fix index to start with 0

- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorService.java
- api/src/main/java/org/terrakube/api/repository/GlobalVarRepository.java
> feat: Support to add a default executor at the organization level as global variable

- api/pom.xml
- executor/pom.xml
- registry/pom.xml
> fix: Add missing AWS STS dependency (#1736)

- ui/package.json
- ui/public/index.html
- ui/src/index.js
- ui/yarn.lock
https://github.com/AzBuilder/terrakube/issues/1729
> deps: bundle github-markdown-css as part of ui

- .gitpod.Dockerfile
- api/src/main/java/org/terrakube/api/plugin/datasource/PostgresAwsIamAuthDataSource.java
- ui/src/index.js
- fix github-markdown-css theme
- fix code smell
- update java in gitpod
> fix: change github-markdown-css theme to light

- api/src/main/java/org/terrakube/api/plugin/scheduler/ScheduleJob.java
Fixes https://github.com/AzBuilder/terrakube/issues/1770
> fix: new jobs should wait for older jobs awaiting approval

- ui/src/domain/Home/App.js
- ui/src/domain/Organizations/Details.jsx
> Fix: Can't Disable a Workspace Filter

- ui/src/domain/Modules/Details.jsx
Enhancing the format for the inputs and outputs:
- Improved styling for input and output tables with consistent padding, left-aligned text, and top vertical alignment for headers and cells.
- Added table borders to the input and output tables.
- Enhanced copy functionality by adding copyable for input and output names.
- fixes #1815
> feat: enhance module inputs and outputs format

- ui/package.json
- ui/yarn.lock
Reverts AzBuilder/terrakube#1862
> Revert "deps: bump react-router-dom from 6.28.0 to 7.3.0 in /ui"

- api/src/main/resources/db/changelog/local/changelog-2.26.0-cli-address.xml
Fix #1906
Change type in liquibase script, tested with postgresql with docker
```shell
2025-03-18T14:38:05.289Z  INFO 8947 --- [           main] o.t.a.p.d.DataSourceAutoConfiguration    : DataSourceType: POSTGRESQL
2025-03-18T14:38:05.289Z  INFO 8947 --- [           main] o.t.a.p.d.DataSourceAutoConfiguration    : postgresql datasource using SSL Mode: disable
2025-03-18T14:38:16.987Z  INFO 8947 --- [           main] liquibase.changelog                      : Creating database history table with name: public.databasechangelog
2025-03-18T14:38:18.576Z  INFO 8947 --- [           main] liquibase.changelog                      : Reading from public.databasechangelog
2025-03-18T14:38:20.778Z  INFO 8947 --- [           main] liquibase.snapshot                       : Creating snapshot …
```
> fix: Change type in migration script

- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.26.0-module-vars-size.xml
> fix: Add new changelog for module column  size modification  #1954.

- .github/workflows/pull_request_ui.yml
- ui/src/config/monacoConfig.ts
- ui/src/config/themeConfig.ts
- ui/src/domain/Home/App.tsx
- ui/src/domain/Home/MainMenu.tsx
- ui/src/domain/Modules/Details.tsx
- ui/src/domain/Modules/List.tsx
- ui/src/domain/Settings/Actions.tsx
- ui/src/domain/Settings/AddTemplate.tsx
- ui/src/domain/Settings/AddVCS.tsx
- ui/src/domain/Settings/EditTemplate.tsx
- ui/src/domain/Settings/General.tsx
- ui/src/domain/Settings/SSHKeys.tsx
- ui/src/domain/Settings/VCS.tsx
- ui/src/domain/Workspaces/Create.tsx
- ui/src/domain/Workspaces/Details.tsx
- ui/src/domain/Workspaces/States.tsx
- ui/src/domain/Workspaces/Variables.tsx
- ui/src/modules/organizations/components/OrganizationGrid/OrganizationGrid.css
- ui/src/modules/organizations/components/OrganizationGrid/OrganizationGridItem.tsx
- ui/src/modules/user/UserSettingsPage.tsx
- ui/src/modules/user/components/ThemeSection/ThemeSection.css
- ui/src/modules/user/components/ThemeSection/ThemeSection.tsx
- ui/src/modules/workspaces/components/WorkspaceCard.tsx
- ui/src/modules/workspaces/components/WorkspaceFilter.tsx
- fixed the linter issues
- fixed the PR github action for UI
> fix: fixed linter issues in ui

- ui/package.json
- ui/src/domain/Home/App.tsx
- ui/yarn.lock
- Replace BrowserRouter with createBrowserRouter and RouterProvider
- Update route configuration to use data-based format
- Update react-router-dom dependency from v6.28.0 to v7.4.1
> feat: migrate to React Router v7.4.1

- ui/src/ActionLoader.tsx
fix issue from migration from vite
> fix: action loader

- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.26.0-vars-size.xml
- ui/src/domain/Settings/GlobalVariables.tsx
- ui/src/domain/Workspaces/Variables.tsx
Would like variables to hold larger values, private keys etc.
Current "input" UI element doesn't seem to work with multiline inputs
> feat: change variables size

- api/src/main/java/org/terrakube/api/rs/workspace/Workspace.java
- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.26.0-add-workspace-column-fix.xml
Related to the issue describe here
https://github.com/AzBuilder/terrakube/pull/2052#issue-2999392560
> fix: Fix column name in workspace table

- ui/src/domain/Home/App.tsx
- ui/src/domain/Settings/CollectionItems.tsx
- ui/src/domain/Settings/CollectionReferences.tsx
- ui/src/domain/Settings/CreateEditCollection.tsx
- ui/src/domain/Settings/Settings.tsx
- ui/src/domain/Settings/VariableCollections.tsx
> feat: add variable collection to organization settings

- ui/src/domain/Home/App.tsx
- ui/src/domain/Home/MainMenu.tsx
- ui/src/domain/Organizations/IconSelector.tsx
- ui/src/domain/Settings/AddVCS.tsx
- ui/src/domain/Settings/Agents.tsx
- ui/src/domain/Settings/CollectionItems.tsx
- ui/src/domain/Settings/CreateEditCollection.tsx
- ui/src/domain/Settings/EditTeam.tsx
- ui/src/domain/Settings/Settings.tsx
- ui/src/domain/Settings/TeamPermissions.css
- ui/src/domain/Settings/TeamPermissions.tsx
- ui/src/domain/Workspaces/Details.tsx
- ui/src/domain/Workspaces/Settings/General.tsx
- ui/src/domain/Workspaces/Settings/Webhook.tsx
- ui/src/domain/Workspaces/Settings/WorkspaceSettings.tsx
- ui/src/domain/Workspaces/Variables.tsx
- ui/src/modules/organizations/OrganizationDetailsPage.tsx
- ui/src/modules/organizations/OrganizationsPickerPage.tsx
- ui/src/modules/organizations/components/OrganizationGrid/OrganizationGridItem.tsx
This PR:
- fixes multiple issues in the UI after the vite migration
- Improves organization settings structure using groups
- Improves the Teams permissions page
- Simplify the Variables page in workspace
> feat: enhanced ui experience

- ui/src/domain/Settings/EditTeam.tsx
This will fix the issue to show the token list in the UI
fix #2178
> fix: Show team tokens correctly in the UI

- registry/src/main/java/org/terrakube/registry/service/module/ModuleServiceImpl.java
> fix: registry parameter mismatch

- registry/src/main/java/org/terrakube/registry/service/module/ModuleServiceImpl.java
> fix: registry parameter mismatch (#2222)

- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ephemeral/EphemeralExecutorService.java
Currently did not find this possible.
Tried to follow style used in nodeSelector or Annotations logic
> feat: Allow specifying securityContext for Ephemeral Executor pods

- api/pom.xml
- executor/pom.xml
- pom.xml
- registry/pom.xml
Related to https://github.com/terrakube-io/terrakube/pull/2269
> fix: SSH workspaces/modules failing for missing dependency

- .gitpod.Dockerfile
- api/src/main/java/io/terrakube/api/plugin/vcs/provider/gitlab/GitLabWebhookService.java
- api/src/test/java/io/terrakube/api/VcsTests.java
> feat: refactor gitlab project id search to use pagination

- api/src/main/java/io/terrakube/api/plugin/scheduler/ScheduleJob.java
- api/src/main/java/io/terrakube/api/plugin/scheduler/inactive/InactiveJobs.java
- api/src/main/java/io/terrakube/api/plugin/vcs/WebhookService.java
- api/src/main/java/io/terrakube/api/plugin/vcs/provider/gitlab/GitLabWebhookService.java
- api/src/main/java/io/terrakube/api/plugin/vcs/provider/gitlab/GitlabCommitStatus.java
- api/src/test/java/io/terrakube/api/VcsTests.java
This will allow to show the commit status like this in gitlab once you enabled the webhooks.
It also allow to click the button and get redirected to terrakube job
> feat: gitlab commit status

- api/src/main/java/io/terrakube/api/plugin/scheduler/module/ModuleRefreshService.java
- api/src/main/java/io/terrakube/api/repository/ModuleRepository.java
fix #2393 
Related to this change #2324
> fix: Refresh module init method is failing for disabled org

- api/src/main/java/io/terrakube/api/plugin/scheduler/job/tcl/executor/ephemeral/EphemeralExecutorService.java
This will allow to set additional environment variables used when creating the job for the ephemeral executor using EPHEMERAL_JOB_ENV_VARS at the workspace level
For example it can be used to pass [redis ssl information](https://docs.terrakube.io/getting-started/deployment/external-redis) like:
TerrakubeRedisSSL=true
TerrakubeRedisTruststorePath=/layers/paketo-buildpacks_bellsoft-liberica/jre/lib/security/cacerts
TerrakubeRedisTruststorePassword=changeit
ExecutorEphemeralSecret=terrakube-executor-secrets-ephemeral
```
EPHEMERAL_JOB_ENV_VARS=TerrakubeRedisSSL=true;TerrakubeRedisTruststorePath=/layers/paketo-buildpacks_bellsoft-liberica/jre/lib/security/cacerts;TerrakubeRedisTruststorePassword=changeit;ExecutorEphemeralSecret=terrakube-executor-secrets-ephemeral
```
Example:
> feat: Add EPHEMERAL_JOB_ENV_VARS variable to set additional values to ephemeral executor
