- api-job/src/main/java/org/azbuilder/api/schedule/JobService.java
- api-job/src/main/java/org/azbuilder/api/schedule/ScheduleJobService.java
- api-job/src/main/java/org/azbuilder/api/schedule/yaml/Flow.java
- api-job/src/main/java/org/azbuilder/api/schedule/yaml/FlowType.java
- api/src/main/java/org/azbuilder/api/rs/checks/job/TeamApproveJob.java
- api/src/main/java/org/azbuilder/api/rs/job/Job.java
- api/src/main/java/org/azbuilder/api/rs/job/JobStatus.java
- api/src/main/resources/db/changelog/local/changelog-1.6.xml
- api/src/test/java/org/azbuilder/api/JobTests.java
Add support to stop a job for an approval using a new terrakube configuration language definition.
Example:
```yaml
flow:
- type: "terraformPlan"
step: 100
commands:
- runtime: "GROOVY"
priority: 100
after: true
script: |
import Infracost
String credentials = "version: \"0.1\"\n" +
"api_key: $INFRACOST_KEY \n" +
"pricing_api_endpoint: https://pricing.api.infracost.io"
new Infracost().loadTool(
"$workingDirectory",
"$bashToolsDirectory", 
"0.9.11",
credentials)
"Infracost Download Completed..."
- runtime: "BASH"
priority: 200
after: true
script: |
terraform show -json terraformLibrary.tfPlan > plan.json 
infracost breakdown --path plan.json
- type: "approval"
team: "AZB_ADMIN"
step: 200
- type: "terraformApply"
step: 300
```
To continue the job execution the team will have to update the …
> Adding support for approvals inside jobs

- api/src/main/java/org/azbuilder/api/plugin/scheduler/configuration/QuartzAutoConfiguration.java
- api/src/main/resources/application.properties
This should fix the cluster configuration issue and Fixes #97 
````
Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
NOT STARTED.
Currently in standby mode.
Number of jobs executed: 0
Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 10 threads.
Using job-store 'org.springframework.scheduling.quartz.LocalDataSourceJobStore' - which supports persistence. and is clustered.
````
> Fix cluster configuration quartz

- pom.xml
- registry/src/main/java/org/azbuilder/registry/service/git/GitServiceImpl.java
Validating if the remote repository is using tags that begins with "v" so the registry can import the module correctly
Example: 
- https://github.com/terraform-aws-modules/terraform-aws-vpc
> Fix tag registry

- api/src/main/java/org/azbuilder/api/plugin/scheduler/ScheduleJob.java
- api/src/main/java/org/azbuilder/api/plugin/scheduler/ScheduleJobService.java
- api/src/main/java/org/azbuilder/api/rs/hooks/job/JobManageHook.java
- api/src/main/java/org/azbuilder/api/rs/job/Job.java
- api/src/main/java/org/azbuilder/api/rs/job/JobStatus.java
- executor/src/main/java/org/azbuilder/executor/service/status/UpdateJobStatusImpl.java
The following request will ***cancel*** a running job and will prevent all pending job steps to continue executing.
```
PATCH {{server}}/api/v1/organization/{{organizationId}}/job/{{jobId}}
{
"data": {
"type": "job",
"id": "{{jobId}}",
"status": "cancelled"
}
}
}
```
Improving these logic:
- When the job scheduler in the API checks the status ***cancelled*** it will mark all pending job steps as ***"cancelled"*** and delete the job context from quartz.
- When the executor finishes executing a job step it will validate if the status of the job is ***cancelled***
Limitation:
- Once the job is running inside the executor the [terraform spring boot starter](https://github.com/AzBuilder/terraform-spring-boot/issues/24) does not allow to cancel any terraform operation and …
> Improving logic to cancel a running job

- README.md
- api/pom.xml
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorService.java
- api/src/main/java/org/terrakube/api/plugin/ssh/TerrakubeSshdSessionFactory.java
- api/src/main/java/org/terrakube/api/rs/Organization.java
- api/src/main/java/org/terrakube/api/rs/checks/ssh/ReadPrivateKey.java
- api/src/main/java/org/terrakube/api/rs/checks/ssh/TeamManageSsh.java
- api/src/main/java/org/terrakube/api/rs/checks/ssh/TeamViewSsh.java
- api/src/main/java/org/terrakube/api/rs/module/Module.java
- api/src/main/java/org/terrakube/api/rs/ssh/Ssh.java
- api/src/main/java/org/terrakube/api/rs/ssh/SshType.java
- api/src/main/java/org/terrakube/api/rs/workspace/Workspace.java
- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.6.0-ssh.xml
- api/src/test/java/org/terrakube/api/ModuleTests.java
- api/src/test/java/org/terrakube/api/OrganizationTests.java
- api/src/test/java/org/terrakube/api/WorkspaceTests.java
- executor/pom.xml
- executor/src/main/java/org/terrakube/executor/service/workspace/SetupWorkspaceImpl.java
- registry/pom.xml
- registry/src/main/java/org/terrakube/registry/service/git/GitServiceImpl.java
- registry/src/main/java/org/terrakube/registry/service/module/ModuleServiceImpl.java
- scripts/template/thunder-tests/thunderEnvironment.json
- thunder-tests/thunderCollection.json
- thunder-tests/thunderclient.json
- ui/src/domain/Modules/Details.jsx
- ui/src/domain/Organizations/Details.jsx
Including support to use SSH Keys (RSA and ED25519) inside the organizations, now Terrakube can authenticate with private repositories without using oAuth applications.
Only users inside teams with "Manage VCS settings" will be able to create SSH keys
Elide now expose the SSH endpoint:
```
POST {{terrakubeApi}}/api/v1/organization/{{organizationId}}/ssh
{
"data": {
"type": "ssh",
"name": "SSH KEY NAME",
"description": "SSH KEY DESCRIPTION",
"privateKey": "{{sshPrivateKey}}", 
"sshType": "{{sshKeyType}}"
}
}
}
```
> sshType field can be ***rsa*** or ***ed25519***
> When sending the private key please include ***"\n"*** at the end of each line
To use the SSH support in modules the ***source***  should be used like ***"git@github.com:AzBuilder/terrakube-docker-compose.git"*** …
> Add SSH Keys support for modules and workspaces

- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorContext.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorService.java
- api/src/main/java/org/terrakube/api/rs/workspace/Workspace.java
- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.6.0-workspace-folder.xml
- coverage/pom.xml
- executor/src/main/java/org/terrakube/executor/service/mode/TerraformJob.java
- executor/src/main/java/org/terrakube/executor/service/workspace/SetupWorkspaceImpl.java
- pom.xml
- ui/src/domain/Workspaces/Create.jsx
- ui/src/domain/Workspaces/Details.jsx
Adding support to handle multiple workspaces using the same git repository using "folders".
Including new "folder" field
```
POST  {{server}}/api/v1/organization/{{organizationId}}/workspace
{
"data": {
"type": "workspace",
"name": "Sample SSH",
"source": "git@github.com:XXXX/terrakube-workspace.git",
"branch": "main",
"terraformVersion": "1.0.11",
"folder": "/folder1/folder2"
}
}
```
Adding field to setup the workspace folder inside the git repository.
Include option to update the workspace folder.
Closes #217
> Adding support to handle workspace inside the repository

- api/src/main/resources/application-demo.properties
- api/src/main/resources/application.properties
- scripts/setupDevelopmentEnvironment.sh
Sometimes we need to define a custom name for the Terrakube administrator group. 
- For example when using Github Authentication the groups claim in the Dex token is define like "GithubOrganizationName:GithubTeamName"
- When using the Google Cloud Identity authentication the group claim is define like "GROUP_NAME@yourdomain.com"
A new environment variable ***TERRAKUBE_ADMIN_GROUP*** is added to handle this cases, if the environment variable is not define the default name "TERRAKUBE_ADMIN" will be used.
If we need to define a custom name in GITPOD you only need to change the following line in ***.envApi file***
> Allow custom admin group name

- api/src/main/java/org/terrakube/api/plugin/scheduler/ScheduleJob.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/ScheduleJobService.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/ScheduleJobTrigger.java
- api/src/main/java/org/terrakube/api/rs/checks/job/TeamManageJob.java
- api/src/main/java/org/terrakube/api/rs/checks/job/TeamViewJob.java
- api/src/main/java/org/terrakube/api/rs/hooks/job/JobManageHook.java
- api/src/main/java/org/terrakube/api/rs/job/Job.java
- api/src/main/java/org/terrakube/api/rs/workspace/Workspace.java
- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.6.0-workspace-lock.xml
- api/src/test/java/org/terrakube/api/JobTests.java
- api/src/test/java/org/terrakube/api/ServerApplicationTests.java
- thunder-tests/thunderclient.json
- ui/src/domain/Workspaces/Details.jsx
Add new option to lock/unlocked workspace inside organizations
```
POST {{terrakubeApi}}/api/v1/organization/{{organizationId}}/workspace
{
"data": {
"type": "workspace",
"name": "Docker Compose Sample",
"source": "https://github.com/AzBuilder/terrakube-docker-compose.git",
"branch": "main",
"folder": "/",
"locked": "true",
"terraformVersion": "1.0.11"
}
}
}
```
Add option to lock/unlock in workspace settings. 
If a workspace is using "locked=true" all new jobs will return 403 when doing the request
```
POST {{terrakubeApi}}/api/v1/organization/{{organizationId}}/job
```
Fixes #209  #184
> Lock/Unlocked Workspace

- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.6.0-team-update.xml
When using Google Identity the groups name include the @domain and the name sometimes can be quite long
> Update length for team name

- executor/src/main/java/org/terrakube/executor/service/executor/ExecutorJobImpl.java
- executor/src/main/java/org/terrakube/executor/service/status/UpdateJobStatusImpl.java
- executor/src/main/java/org/terrakube/executor/service/terraform/TerraformExecutorServiceImpl.java
- ui/src/domain/Jobs/Details.jsx
- ui/src/domain/Organizations/Details.jsx
- ui/src/domain/Workspaces/Details.jsx
Correctly show when a terraform operation failed in the UI and stop flow execution when an error is detected when running the Terrakube Configuration Language flow
> Improve error handling for Terraform Operations (Plan/Apply/Destroy)

- .gitignore
- .gitpod.yml
- api/pom.xml
- bindings/ca-certificates/type
- executor/pom.xml
- pom.xml
- registry/pom.xml
- scripts/build/generateSampleCaCerts.sh
- scripts/build/terrakubeBuild.sh
Fix POM configuration to allow adding custom CA certificates using the following folder  "bindings/ca-certificates". 
> Certificates should be in PEM format.
When running the build using the command "mvn spring-boot:build-image" the certificates are loaded inside the system trustore automatically
A script was added to generate some sample certificates in PEM format "./scripts/build/generateSampleCaCerts.sh" to test it
Once the certificates are added inside the ca-certificates folder we can use the "./scripts/build/terrakubeBuild.sh" to create the new images.
```bash
git clone https://github.com/AzBuilder/terrakube
cd terrakube
mv EXAMPLE.pem bindings/ca-certificates
./scripts/build/terrakubeBuild.sh
``` 
Reference: 
https://stackoverflow.com/questions/68720570/how-to-embed-ca-certificates- …
> Fix build setup to allow custom CA certs

- api/src/main/java/org/terrakube/api/plugin/scheduler/ScheduleVcs.java
- api/src/main/java/org/terrakube/api/plugin/vcs/TokenService.java
- api/src/main/java/org/terrakube/api/plugin/vcs/provider/GetAccessToken.java
- api/src/main/java/org/terrakube/api/plugin/vcs/provider/azdevops/AzDevOpsTokenService.java
- api/src/main/java/org/terrakube/api/plugin/vcs/provider/bitbucket/BitbucketTokenService.java
- api/src/main/java/org/terrakube/api/plugin/vcs/provider/github/GitHubTokenService.java
- api/src/main/java/org/terrakube/api/plugin/vcs/provider/gitlab/GitLabTokenService.java
- api/src/main/java/org/terrakube/api/repository/VcsRepository.java
- api/src/main/java/org/terrakube/api/rs/vcs/Vcs.java
- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.8.0-vcs-callback.xml
- pom.xml
- scripts/template/thunder-tests/thunderEnvironment.json
- thunder-tests/thunderclient.json
Adding a new field inside VCS connections to allow a custom callback instead of using the VCS id, this will allow to define the callback from the UI when need it.
```
POST {{terrakubeApi}}/api/v1/organization/{{organizationId}}/vcs
{
"data": {
"type": "vcs",
"name": "vcsGitHubCustom",
"description": "vcsGitHubDescription",
"vcsType": "GITHUB",
"clientId": "{{githubClientId}}",
"clientSecret": "{{githubClientSecret}}",
"callback": "{{githubCallback}}"
}
}
}
```
> Allow custom callback in VCS

- api/src/main/java/org/terrakube/api/plugin/scheduler/ScheduleJob.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/model/FlowType.java
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
- api/src/main/resources/db/changelog/demo-data/simple.xml
- executor/pom.xml
- executor/src/main/java/org/terrakube/executor/service/executor/ExecutorJobImpl.java
- executor/src/main/java/org/terrakube/executor/service/terraform/TerraformExecutor.java
- executor/src/main/java/org/terrakube/executor/service/terraform/TerraformExecutorServiceImpl.java
This will allow to run a remote Destroy in Terrakube from the Terraform CLI
```terraform
terraform {
backend "remote" {
hostname = "8080-azbuilder-terrakube-is9q8gqdg8x.ws-us84.gitpod.io"
workspaces {
name = "workspace1"
}
}
}
resource "random_string" "random" {
length           = 16
special          = true
override_special = "/@£$"
}
```
Example
```bash
terraform init
terraform plan
terraform destroy
```
> Terraform Remote Backend Support (Destroy)

- api/src/main/java/org/terrakube/api/plugin/manage/OrganizationManageService.java
- api/src/main/resources/db/changelog/demo-data/aws.xml
- api/src/main/resources/db/changelog/demo-data/azure.xml
- api/src/main/resources/db/changelog/demo-data/gcp.xml
- api/src/main/resources/db/changelog/demo-data/simple.xml
All new organizations will be created with the templates to use "Remote Backend", this can be customized later
- Terraform Apply from Terraform CLI
```yaml
flow:
- type: "terraformPlan"
name: "Terraform Plan from Terraform CLI"
step: 100
- type: "approval"
name: "Approve Plan from Terraform CLI"
step: 150
team: "TERRAFORM_CLI"
- type: "terraformApply"
name: "Terraform Apply from Terraform CLI"
step: 200
```
- Terraform Destroy from Terraform CLI
```yaml
flow:
- type: "terraformPlanDestroy"
name: "Terraform Plan Destroy from Terraform CLI"
step: 100
- type: "approval"
name: "Approve Plan from Terraform CLI"
step: 150
team: "TERRAFORM_CLI"
- type: "terraformApply"
name: "Terraform Apply from Terraform CLI"
step: 200
```
> Adding remote backend templates in new organizations

- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeController.java
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
This will fix the discard logic when using the terraform remote backend and cancel the job internally.
> Fix discard logic for remote state backend

- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/TclService.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/model/CommandConfig.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/model/ImportComands.java
Adding support to import template logics using an external git repository.
Example before template import:
```yaml
flow:
- type: "terraformPlan"
step: 100
commands:
- runtime: "GROOVY"
priority: 100
before: true
script: |
import TerraTag
new TerraTag().loadTool(
"$workingDirectory",
"$bashToolsDirectory",
"0.1.30")
"Terratag download completed"
- runtime: "BASH"
priority: 200
before: true
script: |
cd $workingDirectory
terratag -tags="{\"environment_id\": \"development\"}"
- type: "terraformApply"
step: 300
```
Using templates import:
```yaml
flow:
- type: "terraformPlan"
step: 100
importComands:
repository: "https://github.com/AzBuilder/terrakube-extensions"
folder: "templates/terratag"
branch: "import-template"
- type: "terraformApply"
step: 200
```
The sample template can be found …
> Import template logic

- ui/Dockerfile
- ui/README.md
- ui/docker-compose.yml
The container for the UI was running as "root" user.
The Dockerfile now is using the bitnami/nginx image and is running as user 1001
The env-config.js should be mount as a volume to load the parameters needed for the react application instead of running the script to generate the file
Example using docker-compose:
```yaml
version: "3.8"
services:
terrakube-ui:
image: terrakube-ui:latest
container_name: terrakube-ui
volumes:
- ./env-config.js:/app/env-config.js
ports:
- 8080:8080 
```
> Simplify Dockerfile UI using bitnami/nginx

- api/src/main/java/org/terrakube/api/plugin/json/TerraformJsonController.java
- api/src/main/java/org/terrakube/api/plugin/json/TerraformJsonProperties.java
- api/src/main/resources/application-demo.properties
- api/src/main/resources/application.properties
- executor/pom.xml
- executor/src/main/resources/application.properties
- pom.xml
- scripts/setupDevelopmentEnvironment.sh
- scripts/setupDevelopmentEnvironmentAzure.sh
- scripts/setupDevelopmentEnvironmentGcp.sh
- scripts/setupDevelopmentEnvironmentMinio.sh
Terrakube will support terraform cli custom builds or custom cli mirrors, the only requirement is to expose an endpoint with the following structure
Example Endpoint: https://eov1ys4sxa1bfy9.m.pipedream.net/
```json
{
"name":"terraform",
"versions":{
"1.3.9":{
"builds":[
{
"arch":"amd64",
"filename":"terraform_1.3.9_linux_amd64.zip",
"name":"terraform",
"os":"linux",
"url":"https://releases.hashicorp.com/terraform/1.3.9/terraform_1.3.9_linux_amd64.zip",
"version":"1.3.9"
}
],
"name":"terraform",
"shasums":"terraform_1.3.9_SHA256SUMS",
"shasums_signature":"terraform_1.3.9_SHA256SUMS.sig",
"shasums_signatures":[
"terraform_1.3.9_SHA256SUMS.72D7468F.sig",
"terraform_1.3.9_SHA256SUMS.sig"
],
"version":"1.3.9"
}
}
}
```
The API and Executor component will use the environment variable …
> Support for custom terraform cli builds

- api/src/main/java/org/terrakube/api/plugin/scheduler/ScheduleJob.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/model/FlowType.java
Adding support to disable a workspace from inside the template.
```yaml
flow:
- type: "terraformDestroy"
step: 100
- type: "disableWorkspace"
step: 200
```
> This is usefull when we want to delete a workspace automatically after a terraform destroy
> Disable workspace from templates

- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeController.java
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
- api/src/main/java/org/terrakube/api/plugin/storage/StorageTypeService.java
- api/src/main/java/org/terrakube/api/plugin/storage/aws/AwsStorageTypeServiceImpl.java
- api/src/main/java/org/terrakube/api/plugin/storage/azure/AzureStorageTypeServiceImpl.java
- api/src/main/java/org/terrakube/api/plugin/storage/controller/TerraformStateController.java
- api/src/main/java/org/terrakube/api/plugin/storage/gcp/GcpStorageTypeServiceImpl.java
- api/src/main/java/org/terrakube/api/plugin/storage/local/LocalStorageTypeServiceImpl.java
- executor/src/main/java/org/terrakube/executor/plugin/tfstate/local/LocalTerraformStateImpl.java
Adding support to migrate the state to terrakube using 
```bash
terraform init -migrate-state
```
This is usefull for migrating the state from other storage backends like terraform cloud
Initial setup
```terraform
terraform {
backend "remote" {
hostname = "app.terraform.io"
organization = "XXXXXX"
workspaces {
name = "migrate-state"
}
}
}
```
When running the flag "-migrate-state"
```terraform
terraform {
backend "remote" {
hostname = "8080-azbuilder-terrakube-q8aleg88vlc.ws-us94.gitpod.io"
organization = "XXXXXX"
workspaces {
name = "migrate-state"
}
}
}
```
The state from terraform was copied to the local storage backend
> Terraform init -migrate-state (Local Storage)

- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeController.java
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
- api/src/main/java/org/terrakube/api/plugin/state/WellKnownWebServiceImpl.java
- scripts/setupDevelopmentEnvironmentMinio.sh
Adding support to use terraform init with the cloud block like the following example:
```terraform
terraform {
cloud {
hostname = "8080-azbuilder-terrakube-sscrnu9jbie.ws-us99.gitpod.io"
workspaces {
name = "samplecloud"
}
}
}
```
> By default the terraform CLI does not send the terraform version while creating the workspace, by default terrakube will set 1.4.6.
> Support Cloud Block (Terraform Init)

- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeController.java
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
- api/src/main/java/org/terrakube/api/plugin/state/model/runs/RunsData.java
- api/src/main/java/org/terrakube/api/plugin/state/model/runs/WorkspaceModel.java
- thunder-tests/thunderCollection.json
- thunder-tests/thunderclient.json
Adding support to use terraform plan/apply/destroy with the cloud block like the following example:
```terraform
terraform {
cloud {
hostname = "8080-azbuilder-terrakube-sscrnu9jbie.ws-us99.gitpod.io"
workspaces {
name = "samplecloud"
}
}
}
```
> By default the terraform CLI does not send the terraform version while creating the workspace, by default terrakube will set 1.4.6.
> Support Cloud Block (Terraform Plan/Apply/Destroy)

- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
This patch fixes the error:
java.lang.IllegalArgumentException: Illegal base64 character 2b
The base64 state payload suffering errors in decode.
> Fix | fixing the errors in decode state payload

- ui/src/domain/Modules/Create.jsx
- ui/src/domain/Workspaces/Create.jsx
Repository URL ending in ".git" should be optional
Fix #444
> URL with .git is optional

- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeController.java
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
- api/src/main/java/org/terrakube/api/plugin/state/model/workspace/WorkspaceList.java
- api/src/main/java/org/terrakube/api/plugin/state/model/workspace/tags/TagDataList.java
- api/src/main/java/org/terrakube/api/plugin/state/model/workspace/tags/TagModel.java
- api/src/main/java/org/terrakube/api/repository/TagRepository.java
- api/src/main/java/org/terrakube/api/repository/WorkspaceTagRepository.java
- api/src/main/resources/db/changelog/changelog-demo.xml
- api/src/main/resources/db/changelog/demo-data/simple-tag.xml
Adding support to use cloud block and tags to find workspaces when running "terraform init"
```terraform
terraform {
cloud {
hostname = "8080-azbuilder-terrakube-md8dylvuzta.ws-us101.gitpod.io"
workspaces {
tags = ["networking", "development"]
}
}
}
```
Adding example data in simple organization to test using terraform remote state or cloud block.
> Initial Support Cloud Block with Tags

- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.15.0-tags-constraint.xml
Fixing the tags constraint to include the **"organization_id and name"** so tag name can be duplicated between organizations.
This will fix the logic in this constraint
https://github.com/AzBuilder/terrakube/blob/main/api/src/main/resources/db/changelog/local/changelog-2.14.0-tags.xml#L44
> Fix contraint tags

- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeController.java
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
- api/src/main/java/org/terrakube/api/plugin/state/model/runs/Relationships.java
- api/src/main/java/org/terrakube/api/plugin/state/model/runs/RunEventsModel.java
Fixing issues when using cloud block with Terraform 1.5.X
Adding missing endpoint "run-events" to fix the issue.
This will fix the issue
> Cloud Block Support for Terraform 1.5.X

- api/src/main/java/org/terrakube/api/plugin/datasource/DataSourceAutoConfiguration.java
- api/src/main/java/org/terrakube/api/plugin/datasource/DataSourceConfigurationProperties.java
- api/src/main/resources/application-demo.properties
- api/src/main/resources/application.properties
Parameter governing the use of SSL. The allowed values are disable, allow, prefer, require, verify-ca, verify-full. Default mode is "disable".
The parameter use the environment variable DatasourceSslMode.
This parameter is only used with postgresql
> Adding SSL mode parameter to postgresql datasource

- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeController.java
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
- api/src/main/java/org/terrakube/api/plugin/state/model/workspace/state/consumers/StateConsumerList.java
- executor/src/main/java/org/terrakube/executor/service/workspace/security/WorkspaceSecurityImpl.java
Adding support to share the terraform state with other workspace inside the same organization using the following:
```terraform
data "terraform_remote_state" "remote_creation_time" {
backend = "remote"
config = {
hostname = "8080-azbuilder-terrakube-vg8s9w8fhaj.ws-us102.gitpod.io"
workspaces = {
name = "simple_tag1"
}
}
}
resource "null_resource" "previous" {}
resource "time_sleep" "wait_30_seconds" {
depends_on = [null_resource.previous]
create_duration = data.terraform_remote_state.remote_creation_time.outputs.creation_time
}
resource "null_resource" "next" {
depends_on = [time_sleep.wait_30_seconds]
}
```
Example:
Fixes #457
> Support to share terraform state between workspaces

- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
This pull request will fix the logic when searching workspace by tags when using cloud block
The workspace should contain the tags, but it wont matter if the workspace has additional tags.
```terraform
terraform {
cloud {
hostname = "8080-azbuilder-terrakube-0mkeox1yjhv.ws-us104.gitpod.io"
workspaces {
tags = ["development", "networking"]
}
}
}
```
For example when using some sample data like the following:
Result when using the Terraform CLI will be:
> Fixing logic when searching tags

- registry/src/main/java/org/terrakube/registry/configuration/authentication/dex/DexWebSecurityAdapter.java
This will fix the issue with the registry and require authentication to use the following endpoints used by the terraform CLI when using the module protocol.
Search version endpoint:
```bash
{{terrakubeRegistry}}/terraform/modules/v1/{{registryModuleOrg}}/{{registryModuleName}}/{{registryModuleProvider}}
```
Get module.zip URL:
```bash
{{terrakubeRegistry}}/terraform/modules/v1/{{registryModuleOrg}}/{{registryModuleName}}/{{registryModuleProvider}}/{{registryModuleVersion}}
```
Searching without token will return 401 error:
Searching using a token:
Using the following will return 401
```terraform
module "iam" { 
source = "8075-azbuilder-terrakube-cebsv4s4ehg.ws-us104.gitpod.io/aws/iam/aws" 
version = "v5.30.0" 
}
```
After terraform login
```bash
terraform login …
```
> Fix Terraform registry authentication logic

- ui/src/domain/Organizations/Details.jsx
Fix logic when the source is "empty" and using the CLI drive workflow
> Fix UI logic CLI driven workflows

- ui/src/domain/Organizations/Details.jsx
Reverts AzBuilder/terrakube#503
And adding missing "branch" property in graphql query
> Adding missing "branch" property in graphql query

- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeController.java
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
Using a team token inside an organization without the team read access will return the following error:
Using a team token inside an organization where the team is present but there is no "[manage worspace](https://docs.terrakube.io/user-guide/organizations/team-management)" permission, will return.
> Improve Team Token Validation (cloud block/remote state)

- ui/src/domain/Modules/Details.jsx
In the 'configuration details' help box on a registry module, there is a hard-coded value of 'app.terrakube.io' for the registry hostname.
This change sets the hostname to the value defined in Terrakube for the Registry URL.
> fix hard-coded hostname in configuration details

- ui/src/domain/Workspaces/Details.jsx
When updating the delete flag to "deleted=true" also change the workspace name using the following logic:
```javascript
let randomLetters = generateRandomString(4)
let deletedName = `${workspace.data.attributes.name.substring(0,21)}_DEL_${randomLetters}`;
console.log(`New deleted name; ${deletedName}`)
const body = {
data: {
type: "workspace",
id: id,
attributes: {
name: deletedName,
deleted: "true",
},
},
};
```
This workaround will allow to reuse the same name for a workspace but it wont delete all the information from the database or the back-end storage.
> Improve delete workspace logic from the UI

- api/src/main/java/org/terrakube/api/plugin/security/authentication/dex/DexWebSecurityAdapter.java
- executor/src/main/java/org/terrakube/executor/service/workspace/SetupWorkspaceImpl.java
- registry/src/main/java/org/terrakube/registry/configuration/authentication/dex/DexWebSecurityAdapter.java
- ui/src/domain/Jobs/Details.jsx
- ui/src/domain/Workspaces/Create.jsx
- ui/src/domain/Workspaces/Details.jsx
Refactor code to remove deprecated WebSecurityConfigurerAdapter to use the new way using @Bean SecurityFilterChain
Tested with terraform 1.5.7
Reference: 
https://spring.io/blog/2022/02/21/spring-security-without-the-websecurityconfigureradapter
https://www.baeldung.com/spring-deprecated-websecurityconfigureradapter
> Remove deprecated WebSecurityConfigurerAdapter

- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
Fix internal token validation when using remote execution using data.terraform_remote_state
Workspace 1 (name=shared1):
```terraform
terraform {
cloud {
hostname = "8080-azbuilder-terrakube-uzxpj6u2gpe.ws-us105.gitpod.io"
workspaces {
tags = ["shared1", "example"]
}
}
}
resource "null_resource" "previous" {}
resource "time_sleep" "wait_30_seconds" {
depends_on = [null_resource.previous]
create_duration = "5s"
}
resource "null_resource" "next" {
depends_on = [time_sleep.wait_30_seconds]
}
output "creation_time" {
value = time_sleep.wait_30_seconds.create_duration
}
```
Workspace 2 (name=shared2)
```terraform
terraform {
cloud {
hostname = "8080-azbuilder-terrakube-uzxpj6u2gpe.ws-us105.gitpod.io"
workspaces {
tags = ["shared2", "example"]
}
} …
```
> Fix remote execution using data.terraform_remote_state

- api/pom.xml
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
- executor/pom.xml
- executor/src/main/java/org/terrakube/executor/service/executor/ExecutorJobImpl.java
- executor/src/main/java/org/terrakube/executor/service/scripts/CommandExecution.java
- executor/src/main/java/org/terrakube/executor/service/scripts/ScriptEngineService.java
- executor/src/main/java/org/terrakube/executor/service/scripts/bash/BashEngine.java
- executor/src/main/java/org/terrakube/executor/service/scripts/groovy/GroovyEngine.java
- executor/src/main/java/org/terrakube/executor/service/terraform/TerraformExecutorServiceImpl.java
- executor/src/main/java/org/terrakube/executor/service/workspace/SetupWorkspaceImpl.java
- executor/src/main/java/org/terrakube/executor/service/workspace/security/WorkspaceSecurity.java
- executor/src/main/java/org/terrakube/executor/service/workspace/security/WorkspaceSecurityImpl.java
- pom.xml
- registry/pom.xml
This will keep all the git repository structure instead of just copy the folders form the "path" parameter from the workspace definition, this will allow to use modules that are inside the same repository.
Fix #431
> Keep repository structure when cloning a GIT workspace

- api/pom.xml
- api/src/main/java/org/terrakube/api/plugin/token/team/TeamTokenController.java
- api/src/main/java/org/terrakube/api/plugin/token/team/TeamTokenService.java
- executor/pom.xml
- registry/pom.xml
- thunder-tests/thunderclient.json
Add support to handle minutes and hours when generating a team token.
Example:
```
POST {{terrakubeApi}}/access-token/v1/teams
Authorization: Bearer (PERSONAL ACCESS TOKEN)
Request Body:
{
"days": "1",
"hours": "6",
"minutes": "30",
"group": "TERRAKUBE_ADMIN",
"description": "Sample PAT"
}
```
Fix #535
> Support to handle minutes and hours in team token

- api/src/main/java/org/terrakube/api/plugin/scheduler/module/DeleteStorageCacheJob.java
- api/src/main/java/org/terrakube/api/plugin/storage/StorageTypeService.java
- api/src/main/java/org/terrakube/api/plugin/storage/aws/AwsStorageTypeServiceImpl.java
- api/src/main/java/org/terrakube/api/plugin/storage/azure/AzureStorageTypeServiceImpl.java
- api/src/main/java/org/terrakube/api/plugin/storage/gcp/GcpStorageTypeServiceImpl.java
- api/src/main/java/org/terrakube/api/plugin/storage/local/LocalStorageTypeServiceImpl.java
- api/src/main/java/org/terrakube/api/rs/hooks/module/ModuleManageHook.java
- api/src/main/java/org/terrakube/api/rs/module/Module.java
Adding the logic to delete the module data from the storage backend when deleting a module from the UI.
Files before deleting the modules from the UI:
Files after delete the modules:
Adding information in the logs:
S3/MINIO
Local
This PR will add support for MINIO, S3 and Local storage backend.
Azure and GCP storage backend will be added later.
> Delete module data from storage backend (Minio/S3/Local)

- api/src/main/java/org/terrakube/api/plugin/storage/gcp/GcpStorageTypeServiceImpl.java
Delete module data from the GCP bucket when deleting a module from the UI.
Before Delete
After Delete:
Logs:
Fix #523
>  Delete module data from gcp storage backend

- api/src/main/java/org/terrakube/api/plugin/scheduler/module/DeleteStorageCacheJob.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/workspace/DeleteStorageBackendJob.java
- api/src/main/java/org/terrakube/api/plugin/softdelete/SoftDeleteService.java
- api/src/main/java/org/terrakube/api/plugin/storage/StorageTypeService.java
- api/src/main/java/org/terrakube/api/plugin/storage/aws/AwsStorageTypeServiceImpl.java
- api/src/main/java/org/terrakube/api/plugin/storage/azure/AzureStorageTypeServiceImpl.java
- api/src/main/java/org/terrakube/api/plugin/storage/gcp/GcpStorageTypeServiceImpl.java
- api/src/main/java/org/terrakube/api/plugin/storage/local/LocalStorageTypeServiceImpl.java
- api/src/main/java/org/terrakube/api/rs/hooks/module/ModuleManageHook.java
This will delete all workspace data from the backend storage when a workspace is deleted (outputs, terraform state, terraform state json, etc)
Fix #522
> Delete storage backend data when deleting a workspace

- ui/src/domain/Jobs/Create.jsx
- ui/src/domain/Workspaces/Create.jsx
- ui/src/domain/Workspaces/Details.jsx
- ui/src/domain/Workspaces/Workspaces.css
addresses #524 
Adding workspace details to easily check the information (resources count, lock/unlock workspace, terraform version,id, repo url)
Adding resources list based in the latest state
Adding outputs list based in the latest state
> Improving workspace details view

- .github/workflows/pull_request.yml
- .github/workflows/pull_request_ui.yml
- .github/workflows/release.yml
- api/pom.xml
- executor/pom.xml
- registry/pom.xml
Imagen size when using Alpaquita linux as based image
```shell
mvn clean install -Dspring-boot.build-image.skip=false -Dmaven.test.skip=true -Dbuildpack.builder=bellsoft/buildpacks.builder:glibc
```
```shell
user@pop-os:~/git/terrakube$ docker image ls | grep 2.17.0
api-server                               2.17.0               638c3f41d9e5   43 years ago    394MB
executor                                 2.17.0               8d7c7760d51d   43 years ago    338MB
open-registry                            2.17.0               47240ba6106a   43 years ago    332MB
```
Note: Executor  does not include git, running modules like the following wont be supported:
```terraform
module "consul" {
source = "git@github.com:hashicorp/example.git"
}
```
Imagen size when using Ubuntu Jammy as based image …
> Experimental Alpaquita Linux Support 

- docker-compose/docker-compose.yaml
- telemetry-compose/docker-compose.yaml
Update docker-compose examples to use version 2.17.0
Update telemetry-compose example that show how to integrate open telemetry with Terrakube to version 2.17.0
> Update docker compose to 2.17.0

- ui/src/domain/Workspaces/Details.jsx
Fix logic if the state has no outputs the resource count in the workspace details and the list of resources are not shown correctly in the UI.
> Fix validation if the state has no outputs in workspace details page

- ui/src/domain/Workspaces/Details.jsx
This will improve the UI validation when the Terraform output is a complex object and not a simple string
Fix #619
> Fix output logic in workspace details

- api/src/main/java/org/terrakube/api/rs/Organization.java
- api/src/main/java/org/terrakube/api/rs/globalvar/Globalvar.java
- api/src/main/java/org/terrakube/api/rs/job/Job.java
- api/src/main/java/org/terrakube/api/rs/job/step/Step.java
- api/src/main/java/org/terrakube/api/rs/module/Module.java
- api/src/main/java/org/terrakube/api/rs/provider/Provider.java
- api/src/main/java/org/terrakube/api/rs/provider/implementation/Implementation.java
- api/src/main/java/org/terrakube/api/rs/provider/implementation/Version.java
- api/src/main/java/org/terrakube/api/rs/ssh/Ssh.java
- api/src/main/java/org/terrakube/api/rs/tag/Tag.java
- api/src/main/java/org/terrakube/api/rs/team/Team.java
- api/src/main/java/org/terrakube/api/rs/template/Template.java
- api/src/main/java/org/terrakube/api/rs/token/pat/Pat.java
- api/src/main/java/org/terrakube/api/rs/vcs/Vcs.java
- api/src/main/java/org/terrakube/api/rs/webhook/Webhook.java
- api/src/main/java/org/terrakube/api/rs/workspace/Workspace.java
- api/src/main/java/org/terrakube/api/rs/workspace/content/Content.java
- api/src/main/java/org/terrakube/api/rs/workspace/history/History.java
- api/src/main/java/org/terrakube/api/rs/workspace/parameters/Variable.java
- api/src/main/java/org/terrakube/api/rs/workspace/schedule/Schedule.java
- api/src/main/java/org/terrakube/api/rs/workspace/tag/WorkspaceTag.java
- pom.xml
This will fix the issue when running Terrakube with mysql 5.7 that is using ***lower_case_table_names=0***
The code is now using the propose solution from [here](https://stackoverflow.com/questions/6218713/hibernate-scheme-naming-differs-between-os)
Fix #603
> Fix mysql case sensitive issue

- api/src/main/java/org/terrakube/api/plugin/scheduler/ScheduleJobTrigger.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorContext.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorService.java
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
- api/src/main/java/org/terrakube/api/plugin/vcs/WebhookService.java
- api/src/main/java/org/terrakube/api/rs/job/Job.java
- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/demo-data/aws.xml
- api/src/main/resources/db/changelog/demo-data/gcp.xml
- api/src/main/resources/db/changelog/demo-data/simple.xml
- api/src/main/resources/db/changelog/local/changelog-2.19.0-allow-refresh.xml
- api/src/main/resources/db/changelog/local/changelog-2.19.0-override-vcs.xml
- executor/pom.xml
- executor/src/main/java/org/terrakube/executor/service/mode/TerraformJob.java
- executor/src/main/java/org/terrakube/executor/service/terraform/TerraformExecutorServiceImpl.java
- pom.xml
Running the following simple terraform using cli-driven workflow:
```
user@pop-os:~/git/simple-terraform$ terraform apply
Running apply in Terraform Cloud. Output will stream here. Pressing Ctrl-C
will cancel the remote apply if it's still pending. If the apply started it
will stop streaming the logs, but will not stop the apply running remotely.
Preparing the remote apply...
To view this run in a browser, visit:
https://8080-azbuilder-terrakube-3it4oxf0vpt.ws-us107.gitpod.io/app/simple/simple-terraform/runs/1
Waiting for the plan to start...
***************************************
Running Terraform PLAN
***************************************
Terraform used the selected providers to generate the following execution
plan. Resource actions are indicated with the following symbols:
+ create …
```
> Allow to use refresh=false in cli-driven workflow

- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorContext.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorService.java
- api/src/main/java/org/terrakube/api/repository/SshRepository.java
- api/src/main/java/org/terrakube/api/rs/workspace/Workspace.java
- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.19.0-vcs-module-ssh.xml
- executor/src/main/java/org/terrakube/executor/service/mode/TerraformJob.java
- executor/src/main/java/org/terrakube/executor/service/terraform/TerraformExecutorServiceImpl.java
- executor/src/main/java/org/terrakube/executor/service/workspace/SetupWorkspaceImpl.java
- ui/src/domain/Workspaces/Details.jsx
This PR will allow to select a SSH key in the workspace setting, this key will be use to download terraform modules using ssh connection.
Adding a new option inside the workspace setting to select which SSH key should be use to download terraform modules like the following example:
```terraform
module "test" {
source = "git@github.com:alfespa17/simple-terraform.git"
}
```
This option can also be use with workspaces with "ssh connection" by default it will be using the SSH key that was selected when creating the workspace but can be used if you want to use a different ssh key for downloading modules.
Fix #640
> SSH keys with VCS connection

- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.19.0-workspace-folder-length.xml
Adding liquibase database changeset to increase size of the folder column in workspace table.
Fix #657
> Fix length folder in workspace table

- registry/src/main/java/org/terrakube/registry/controller/ModuleWebServiceImpl.java
Fix response code in terrakube registry to be able to work correctly with tofu
```
user@pop-os:~/git/simple-terraform$ terraform init
Initializing the backend...
Initializing modules...
Downloading 8075-azbuilder-terrakube-sm2t1umnh4z.ws-us107.gitpod.io/azure/network/azurerm 5.3.0 for network...
- network in .terraform/modules/network
- time_module in module
Initializing provider plugins...
- Reusing previous version of hashicorp/time from the dependency lock file
- Reusing previous version of hashicorp/random from the dependency lock file
- Finding hashicorp/azurerm versions matching ">= 3.0.0, < 4.0.0"...
- Reusing previous version of hashicorp/null from the dependency lock file
- Installing hashicorp/random v3.6.0...
- Installed hashicorp/random v3.6.0 (signed by HashiCorp)
- …
```
> Fix terrakube registry response code

- api/src/main/java/org/terrakube/api/plugin/scheduler/ScheduleJob.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorContext.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorService.java
- api/src/main/java/org/terrakube/api/plugin/vcs/WebhookResult.java
- api/src/main/java/org/terrakube/api/plugin/vcs/WebhookService.java
- api/src/main/java/org/terrakube/api/plugin/vcs/controller/WebHookController.java
- api/src/main/java/org/terrakube/api/plugin/vcs/provider/github/GitHubWebhookModel.java
- api/src/main/java/org/terrakube/api/plugin/vcs/provider/github/GitHubWebhookService.java
- api/src/main/java/org/terrakube/api/repository/JobRepository.java
- executor/src/main/java/org/terrakube/executor/service/mode/TerraformJob.java
- executor/src/main/java/org/terrakube/executor/service/workspace/SetupWorkspaceImpl.java
When having multiple VCS private workspaces validate file changes to trigger a job in a specific wokspace only
The webhook will also generate a job for a particular commit id:
It will also execute jobs in order of creation
> Github Webhook - Validate File changes

- api/src/main/java/org/terrakube/api/plugin/scheduler/ScheduleJob.java
If for some reason a job has been running for more than 6 hours this PR will cancel the job and mark it as failed
> Cancel old jobs

- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorContext.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorService.java
- api/src/main/java/org/terrakube/api/rs/workspace/Workspace.java
- api/src/main/resources/db/changelog/changelog-demo.xml
- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/demo-data/demo-tofu.xml
- api/src/main/resources/db/changelog/local/changelog-2.19.0-workspace-tofu.xml
- executor/pom.xml
- executor/src/main/java/org/terrakube/executor/service/mode/TerraformJob.java
- executor/src/main/java/org/terrakube/executor/service/terraform/TerraformExecutorServiceImpl.java
- ui/src/domain/Workspaces/Details.jsx
Adding option to use OpenTofu inside the workspace settings after creation:
> For now it will require to select 1.6.0 from the dropdown, the dropdown menu will have to be update in order to just show OpenTofu versions
Running a sample vcs with opentofu will show something like the following:
Plan
Apply
Destroy
##
Tofu login:
```shell
user@pop-os:~/git/simple-terraform$ tofu login 8080-azbuilder-terrakube-w63gqxcwyai.ws-us107.gitpod.io
OpenTofu will request an API token for 8080-azbuilder-terrakube-w63gqxcwyai.ws-us107.gitpod.io using OAuth.
This will work only if you are able to use a web browser on this computer to
complete a login process. If not, you must obtain an API token by another
means and configure it in the CLI configuration manually.
If login is successful, OpenTofu will store …
```
> Initial OpenTofu support

- ui/src/domain/Workspaces/Details.jsx
Adding option to change branch in workspace settings after creation.
Fix #655
> Allow to change branch in VCS workspaces

- api/src/main/java/org/terrakube/api/plugin/vcs/provider/gitlab/GitLabWebhookService.java
- api/src/main/java/org/terrakube/api/plugin/vcs/provider/gitlab/GitlabWebhookModel.java
Correctly validate file changes in push events if multiple workspace are using the same repository with a private vcs gitlab connection.
Queue multiple push correctly:
> Gitlab Webhook - Validate File changes

- api/src/main/java/org/terrakube/api/plugin/scheduler/ScheduleJob.java
This PR will fix the validation logic to check if a previous job is running before executing the next job.
Related to [this](https://github.com/orgs/AzBuilder/discussions/714#discussion-6222781)
> Fix validation for previous jobs

- api/src/main/java/org/terrakube/api/plugin/importer/tfcloud/services/WorkspaceService.java
> Improved workspace importer validation for workspaces that don't have JSON State

- api/src/main/java/org/terrakube/api/plugin/security/authentication/dex/DexAuthenticationManagerResolver.java
Fix #742 
This will fix the http code 500 error when sending an expired jwt token, the change will capture correctly the exception "ExpiredJwtException" when executing "Jwts.parserBuilder().build().parseClaimsJwt" and correctly return http code 401
> Fix http 500 error in expired tokens

- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeController.java
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
- api/src/main/java/org/terrakube/api/repository/WorkspaceRepository.java
Fix #717 
Adding support to handle the remote backend with a prefix like the following example:
```terraform
terraform {
backend "remote" {
hostname = "8080-azbuilder-terrakube-7tnuq3gnkgf.ws-us108.gitpod.io"
workspaces {
prefix = "my-app-"
}
}
}
```
Example in the UI, using to workspaces with name prefix "my-app-"
The terraform init will show both workspaces to select and continue with the flow
```shell
user@pop-os:~/git/simple-terraform$ terraform init
Initializing the backend...
The currently selected workspace (default) does not exist.
This is expected behavior when the selected workspace did not have an
existing non-empty state. Please enter a number to select a workspace:
1. 1
2. 2
Enter a value: 1
Successfully configured the backend "remote"! Terraform will …
```
> Support to use remote backend with prefix

- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
Adding missing property "working-directory" when using the following method:
```
GET {{TERRAKUBE_API}}/remote/tfe/v2/organizations/{organizationName}/workspaces/{workspaceName}"
```
This will allow to correctly trigger a job from the CLI in a workspace that is connected to a VCS repository.
Trigger from the CLI
```shell
user@pop-os:~/git/webhook/simple-terraform/work1$ terraform init
Initializing Terraform Cloud...
Initializing modules...
- time_module in ../module
Initializing provider plugins...
- Finding latest version of hashicorp/null...
- Finding latest version of hashicorp/time...
- Finding latest version of hashicorp/random...
- Installing hashicorp/null v3.2.2...
- Installed hashicorp/null v3.2.2 (signed by HashiCorp)
- Installing hashicorp/time v0.10.0...
- Installed …
```
> Adding workspace directory in response

- executor/src/main/java/org/terrakube/executor/service/terraform/TerraformExecutorServiceImpl.java
This will fix the working directory when executing a speculative plan for a workspace that is using a VCS connection
> Fix workdir for speculative plan

- ui/src/domain/Workspaces/Details.jsx
This will improve the logic in the UI to show the resources and outputs when using terraform version below 1.3.X that does not have a `json state representation` when using the CLI driven workflow
Terraform 1.2.7
Terraform 1.5.7
> Improve logic to parse state for terraform below 1.3

- api/src/main/java/org/terrakube/api/plugin/importer/tfcloud/services/WorkspaceService.java
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
- api/src/main/java/org/terrakube/api/plugin/storage/StorageTypeService.java
- api/src/main/java/org/terrakube/api/plugin/storage/aws/AwsStorageTypeServiceImpl.java
- api/src/main/java/org/terrakube/api/plugin/storage/azure/AzureStorageTypeServiceImpl.java
- api/src/main/java/org/terrakube/api/plugin/storage/controller/TerraformStateController.java
- api/src/main/java/org/terrakube/api/plugin/storage/gcp/GcpStorageTypeServiceImpl.java
- api/src/main/java/org/terrakube/api/plugin/storage/local/LocalStorageTypeServiceImpl.java
- executor/pom.xml
- executor/src/main/java/org/terrakube/executor/plugin/tfstate/TerraformState.java
- executor/src/main/java/org/terrakube/executor/plugin/tfstate/aws/AwsTerraformStateImpl.java
- executor/src/main/java/org/terrakube/executor/plugin/tfstate/azure/AzureTerraformStateImpl.java
- executor/src/main/java/org/terrakube/executor/plugin/tfstate/gcp/GcpTerraformStateImpl.java
- executor/src/main/java/org/terrakube/executor/plugin/tfstate/local/LocalTerraformStateImpl.java
- executor/src/main/java/org/terrakube/executor/service/mode/TerraformJob.java
- executor/src/main/java/org/terrakube/executor/service/terraform/TerraformExecutorServiceImpl.java
- ui/src/domain/Workspaces/States.jsx
This PR will create a backup for the raw terraform state (`terraform pull)` in the workspace state history folder after any apply or destroy, instead of just saving the json state representation of the `terraform show` command.
Example MinIO:
Relatd to #740
> Backup Raw State in Workspace History

- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorContext.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorService.java
- api/src/main/java/org/terrakube/api/rs/Organization.java
- api/src/main/java/org/terrakube/api/rs/agent/Agent.java
- api/src/main/java/org/terrakube/api/rs/workspace/Workspace.java
- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.20.0-executor-agent.xml
- thunder-tests/thunderCollection.json
- thunder-tests/thunderclient.json
This PR will allow to have several agents inside an organization to run the remote jobs.
Create organization agent
```
POST {{terrakubeApi}}/api/v1/organization/{{organizationId}}/agent
{
"data": {
"type": "agent",
"name": "sample-agent",
"url": "http://localhost:8090",
"description": "This is a sample agent"
}
}
}
```
Set workspace to use specific agent
```
PATCH {{terrakubeApi}}/api/v1/organization/{{organizationId}}/workspace/{{workspaceId}}/relationships/agent
{
"data": {
"type": "agent",
"id": "f0ddb2e5-c390-4451-bd7f-fe84e74010de"
}
}
```
Remove agent from workspace
```
PATCH {{terrakubeApi}}/api/v1/organization/{{organizationId}}/workspace/{{workspaceId}}/relationships/agent
{
"data":  null
}
```
The logs will show which agent will execute the job like the …
> Support for job agents

- api/pom.xml
- api/src/main/java/org/terrakube/api/plugin/scheduler/module/CacheJob.java
- api/src/main/java/org/terrakube/api/rs/module/GitTagsCache.java
- api/src/main/java/org/terrakube/api/rs/module/Module.java
- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.20.0-registry-monorepo.xml
- executor/pom.xml
- registry/pom.xml
- registry/src/main/java/org/terrakube/registry/plugin/storage/StorageService.java
- registry/src/main/java/org/terrakube/registry/plugin/storage/aws/AwsStorageServiceImpl.java
- registry/src/main/java/org/terrakube/registry/plugin/storage/azure/AzureStorageServiceImpl.java
- registry/src/main/java/org/terrakube/registry/plugin/storage/gcp/GcpStorageServiceImpl.java
- registry/src/main/java/org/terrakube/registry/plugin/storage/local/LocalStorageServiceImpl.java
- registry/src/main/java/org/terrakube/registry/service/git/GitService.java
- registry/src/main/java/org/terrakube/registry/service/git/GitServiceImpl.java
- registry/src/main/java/org/terrakube/registry/service/module/ModuleServiceImpl.java
- ui/src/domain/Modules/Create.jsx
Adding support to publish modules from a monorepo
Adding new fields to set the "folder" and the "tagPrefix" information
Example from monorepo
Folder structure
Module 1
Module 2
Fix #653
> Adding support to publish modules from a monorepo

- docker-compose/api.env
Fix small issue where the docker compose is including a prefix "http://" that is not correct.
Fix #795
> fix docker-compose api hostname

- api/pom.xml
- api/src/main/java/org/terrakube/api/rs/checks/job/TeamManageJob.java
- api/src/test/java/org/terrakube/api/JobTests.java
- docker-compose/api.env
- executor/pom.xml
- registry/pom.xml
This will allow to trigger jobs from the UI that are queue correctly, instead of returning a Http 403 when using the Job endpoint
Fix #804 
Fix small issue in docker compose hostname value
Fix #795
> Fix queue UI

- api/src/main/java/org/terrakube/api/plugin/scheduler/ScheduleJob.java
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
- api/src/main/java/org/terrakube/api/rs/job/Job.java
- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.21.0-auto-apply.xml
Adding support to auto approve the cli driven workflow when using:
```shell
terraform apply --auto-approve
```
```shell
user@pop-os:~/git/simple-terraform$ terraform init
Initializing Terraform Cloud...
Initializing modules...
- time_module in module
Initializing provider plugins...
- Finding latest version of hashicorp/null...
- Finding latest version of hashicorp/time...
- Finding latest version of hashicorp/random...
- Installing hashicorp/null v3.2.2...
- Installed hashicorp/null v3.2.2 (signed by HashiCorp)
- Installing hashicorp/time v0.11.1...
- Installed hashicorp/time v0.11.1 (signed by HashiCorp)
- Installing hashicorp/random v3.6.1...
- Installed hashicorp/random v3.6.1 (signed by HashiCorp)
Terraform has created a lock file .terraform.lock.hcl to record the provider
selections …
```
> Support for --auto-approve flag

- .gitignore
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorService.java
- api/src/main/java/org/terrakube/api/plugin/security/authentication/dex/DexWebSecurityAdapter.java
- api/src/main/java/org/terrakube/api/plugin/token/dynamic/DynamicCredentialsService.java
- api/src/main/java/org/terrakube/api/plugin/token/dynamic/JwksController.java
- api/src/main/java/org/terrakube/api/plugin/token/dynamic/OpenIdConfigurationController.java
- api/src/main/resources/application-demo.properties
- api/src/main/resources/application.properties
- scripts/setupDevelopmentEnvironment.sh
This pull request add support to manage Azure Dynamic Provider credentials so Terrakube can automatically authenticate with Azure without storing any service principal secret.
To use Azure Dynamic Provider credentials we need to genera a public and private key that will be use to generate a validate the federated tokens, we can use the following commands
```
openssl genrsa -out private_temp.pem 2048
openssl rsa -in private_temp.pem -outform PEM -pubout -out public.pem
```
You need to make sure the private key starts with "-----BEGIN PRIVATE KEY-----" if not the following command can be used to transform the private key to the correct format
```
openssl pkcs8 -topk8 -inform PEM -outform PEM -nocrypt -in private_temp.pem -out private.pem
```
The public and private key need to be mounted …
> Azure Dynamic provider credentials support

- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorService.java
- api/src/main/java/org/terrakube/api/plugin/token/dynamic/DynamicCredentialsService.java
- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.21.0-gcp-dynamic.xml
- executor/src/main/java/org/terrakube/executor/service/terraform/TerraformExecutor.java
- executor/src/main/java/org/terrakube/executor/service/terraform/TerraformExecutorServiceImpl.java
- executor/src/main/java/org/terrakube/executor/service/workspace/SetupWorkspaceImpl.java
Adding support to use gcp dynami provider credential support:
Inside our GCP project we need to do the following:
Add a new workload identity federation
Add a name to the identity pool.
Select OIDC , add a provider name, use the terrakube api for the issuer URL and leave the default audience
Setup the provider attributes
the attribute mapping should look like the following:
OIDC 1:
```
assertion.sub
```
Condition CEL
```
assertion.sub.startsWith("organization:TERRAKUBE_ORGANIZATION_NAME:workspace:TERRAKUBE_WORKSPACE_NAME")
```
Once created we can copy the audience and just remove the "https:"
Finally we need to grant access to one particular gcp service account.
We need to define the following env variables inside the workspace configuration:
- ENABLE_DYNAMIC_CREDENTIALS_GCP=true
- …
> GCP Dynamic provider credentials support

- docker-compose/docker-compose.yaml
- docker-compose/ui.env
Remove ui.env is not really need it anymore when using docker-compose
> Remove ui.env in docker-compose [skip ci]

- ui/src/domain/Workspaces/CLIDriven.jsx
Adding hostname in the CLI driven workflow example for remote and cloud backend
Fix #835
> Add hostname in CLI driven workflow example

- api/src/main/java/org/terrakube/api/plugin/token/dynamic/DynamicCredentialsService.java
- executor/src/main/java/org/terrakube/executor/service/workspace/SetupWorkspaceImpl.java
Adding support to use AWS dynamic provider credential support.
We need to define the following environment variables inside the workspace configuration:
- ENABLE_DYNAMIC_CREDENTIALS_AWS=true
- WORKLOAD_IDENTITY_AUDIENCE_AWS=aws.workload.identity
- WORKLOAD_IDENTITY_ROLE_AWS=XXXXXXXXX
- AWS_REGION=XXXXXXXXX
To setup the federeated credentials in AWS we can use the following terraform code:
> The aws_iam_policy can be customize in this case we will use it just to deploy S3 as an example
```terraform
provider "aws" {
}
variable "terrakube_api_hostname" {
type        = string
default     = "terrakube-api.minikube.net"
description = "The terrakube API hostname example: terrakube-api.minikube.net"
}
variable "terrakube_federated_credentials_audience" {
type        = string
default     = …
```
> AWS Dynamic provider credentials support

- .gitignore
- dynamic-credential-setup/gcp/README.md
- dynamic-credential-setup/gcp/datasource.tf
- dynamic-credential-setup/gcp/main.tf
- dynamic-credential-setup/gcp/output.tf
- dynamic-credential-setup/gcp/provider.tf
- dynamic-credential-setup/gcp/variables.tf
Adding small terraform code to setup the dynamic credentials in GCP and how to test using a simple workspace in terrakube using the remote CLI driven workflow
> GCP Dynamic Provider Credentials Setup example with Terraform

- api/src/main/java/org/terrakube/api/plugin/scheduler/ScheduleJob.java
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
- api/src/main/java/org/terrakube/api/rs/job/JobStatus.java
- executor/pom.xml
- executor/src/main/java/org/terrakube/executor/service/executor/ExecutorJobImpl.java
- executor/src/main/java/org/terrakube/executor/service/executor/ExecutorJobResult.java
- executor/src/main/java/org/terrakube/executor/service/status/UpdateJobStatus.java
- executor/src/main/java/org/terrakube/executor/service/status/UpdateJobStatusImpl.java
- executor/src/main/java/org/terrakube/executor/service/terraform/TerraformExecutorServiceImpl.java
- ui/src/domain/Jobs/Details.jsx
- ui/src/domain/Organizations/Details.jsx
- ui/src/domain/Workspaces/Details.jsx
Correctly validate if a plan has no changes, if the plan has no changes then no other operation should run in Terrakube and the CLI complete the job sucessfully
```
user@pop-os:~/git/simple-terraform$ terraform init
Initializing Terraform Cloud...
Initializing modules...
- time_module in module
Initializing provider plugins...
- Finding latest version of hashicorp/random...
- Finding latest version of hashicorp/null...
- Finding latest version of hashicorp/time...
- Installing hashicorp/random v3.6.1...
- Installed hashicorp/random v3.6.1 (signed by HashiCorp)
- Installing hashicorp/null v3.2.2...
- Installed hashicorp/null v3.2.2 (signed by HashiCorp)
- Installing hashicorp/time v0.11.1...
- Installed hashicorp/time v0.11.1 (signed by HashiCorp)
Terraform has created a lock file …
```
> Validate if plan has no changes

- api/pom.xml
- executor/src/main/java/org/terrakube/executor/plugin/tfstate/azure/AzureTerraformStateImpl.java
- executor/src/main/java/org/terrakube/executor/service/status/UpdateJobStatusImpl.java
- pom.xml
Fix failed plan was asking for confirmation and one small issue with the azure backend storage when downloading the terraform plan in the executor logic
> Fix failed plan login in CLI driven workflow 

- ui/src/domain/Workspaces/Import.jsx
With slash in the end of the endpoint, terrakube api returns status code 404
> fix: the endpoint of api importer

- executor/src/main/java/org/terrakube/executor/service/scripts/bash/BashEngine.java
> Fix tofu path when using custom scripts

- api/src/main/resources/application-demo.properties
- api/src/main/resources/application.properties
This commit updates the Elide Swagger configuration in both "application-demo.properties" and "application.properties". The updates change Swagger paths and enablement to conform to the new Elide API Docs configuration, as well as setting the API Docs version to "openapi_3_0".
Fix #1005
> Update Elide Swagger configuration to Elide API Docs

- api/src/main/java/org/terrakube/api/rs/workspace/Workspace.java
- ui/src/domain/Workspaces/Create.jsx
How to reproduce:
1. Create a workspace with a name - for example test-iac, save it
2. Create another workspace with the same name 
3.
> fix: workspace duplicate name handling causes unhandled 500 errors in UI

- api/pom.xml
- api/src/main/java/org/terrakube/api/plugin/scheduler/ScheduleJob.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorService.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ephemeral/EphemeralConfiguration.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ephemeral/EphemeralExecutorService.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ephemeral/K8sClientAutoConfiguration.java
- api/src/main/resources/application-demo.properties
- api/src/main/resources/application.properties
- ephemeral-executor-config/rbac_role.yml
- ephemeral-executor-config/rbac_role_binding.yml
- ephemeral-executor-config/service_account.yml
- executor/src/main/java/org/terrakube/executor/configuration/ExecutorFlagsProperties.java
- executor/src/main/java/org/terrakube/executor/service/executor/ExecutorJobImpl.java
- executor/src/main/java/org/terrakube/executor/service/mode/TerraformJob.java
- executor/src/main/java/org/terrakube/executor/service/mode/batch/BatchModeServiceImpl.java
- executor/src/main/resources/application.properties
- pom.xml
This will allow to run the executor component in `"ephemeral"` mode.
The following environment variables were added in the API:
- ExecutorEphemeralNamespace (Default value: "terrakube")
- ExecutorEphemeralImage (Defatul value: "azbuilder/executor:2.22.0" )
- ExecutorEphemeralSecret (Default value: "terrakube-executor-secrets" )
> The above is basically to control where the job will be created and executed and to mount the secrets required by the executor component
The following environment variables were added in the Executor:
- EphemeralFlagBatch (Default value: "false")
- EphemeralJobData, this contains all the data that the executor need to run.
To use Ephemeral executors we need to create the following configuration:
```yaml
apiVersion: v1
kind: ServiceAccount
metadata:
name: …
```
> Ephemeral Executor Support

- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorService.java
- api/src/main/java/org/terrakube/api/plugin/token/dynamic/DynamicCredentialsService.java
Change logic for logging level in some classes if we need to see the information this can be customize like the following:
`JAVA_TOOL_OPTIONS="-Dlogging.level.org.terrakube.api.plugin.scheduler.job.tcl.executor=DEBUG"`
> Change logging level for some messages

- api/src/main/java/org/terrakube/api/plugin/scheduler/ScheduleJob.java
- api/src/main/java/org/terrakube/api/plugin/vcs/WebhookService.java
- api/src/main/java/org/terrakube/api/plugin/vcs/provider/github/GitHubWebhookService.java
- api/src/main/java/org/terrakube/api/plugin/vcs/provider/github/GithubCommitStatus.java
- api/src/main/java/org/terrakube/api/rs/job/JobVia.java
https://docs.github.com/en/rest/commits/statuses?apiVersion=2022-11-28
Github allows external checks to mark commits with set states, this change does that.
1. Add a JobVia enum class to unify the value of the `via` field
2. Add a GithubCommitStatus enum class to convert from JobStatus to allowed Github commit status.
fix #1069
> feat: #107 send status check back to Github

- api/src/main/resources/application-demo.properties
- api/src/main/resources/application.properties
- executor/src/main/resources/application.properties
This will fix using tofu with ephemeral executors feature. I added a default value for the tofu URL
Fix #1085
> Adding default value for tofu url

- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.22.0-global-vars-size.xml
A new database changelog has been added, "changelog-2.22.0-global-vars-size.xml", which modifies the data type for the column "variable_value" in the "globalvar" table. The new data type would allow larger variable values, with a size limit of 5120 characters.
> Globalvar size

- api/src/main/java/org/terrakube/api/plugin/vcs/WebhookService.java
- api/src/main/java/org/terrakube/api/plugin/vcs/provider/github/GitHubWebhookService.java
The carve-out code for branches in the push event from Github is wrong, need to copy the array from second item.
1. Also break out once a match is found in the branch comparison
> fix: branch name carve out for Github

- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/TclService.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorService.java
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
- api/src/main/java/org/terrakube/api/plugin/vcs/WebhookService.java
- executor/src/main/java/org/terrakube/executor/service/terraform/TerraformExecutorServiceImpl.java
This change extends the folder settings on workspace settings by allowing multiple fields separated by comma, the first path will be used as the default workspace path for runs triggered from UI, the rest of the paths are regex to match against the changed files in a push event sent from VCS providers.
Example folder path: /workspaces/test,modules/.*.tf
related to #703
> feat: support trigger by regex patterns 

- api/src/main/java/org/terrakube/api/rs/hooks/workspace/WorkspaceManageHook.java
Fix issue to disable webhooks for air gapped servers.
Inside the organization we just need to add the following.
Fix #1147
> Fix webhooks for air gapped servers

- api/pom.xml
- pom.xml
- registry/pom.xml
Upgraded Spring Boot from version 3.1.12 to 3.2.8 in the main pom.xml to ensure compatibility with new features and security updates. Also updated JUnit Jupiter API from version 5.7.2 to 5.10.3 in registry/pom.xml, which includes several bug fixes and improvements.
> Update dependency versions in pom.xml files

- api/src/main/java/org/terrakube/api/plugin/vcs/provider/github/GitHubWebhookService.java
GitHub uses the context to differentiate the runs from various systems, it's quite common nowadays that people use single repository to host code that runs from different workspace, even different organization.
This change adds the context to differentiate such runs
> fix: Add more info to context to differentiate runs from workspaces

- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ephemeral/EphemeralConfiguration.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ephemeral/EphemeralExecutorService.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ephemeral/K8sClientAutoConfiguration.java
- api/src/main/resources/application-demo.properties
- api/src/main/resources/application.properties
- pom.xml
Adding option to specify node selector when running the executor component in ephemeral mode.
To use it we need to add the following:
```yaml
api:
env:
- name: JAVA_TOOL_OPTIONS
value: "-Dorg.terrakube.executor.ephemeral.nodeSelector.diskType=ssd -Dorg.terrakube.executor.ephemeral.nodeSelector.nodeType=spot"
```
The above will basically be the equivalent to:
```yaml
nodeSelector:
disktype: ssd
nodeType: spot
```
We just need to add the nodeSelector properties inside the application.property `Dorg.terrakube.executor.ephemeral.nodeSelector.XXX=YYYY`  using  JAVA_TOOL_OPTIONS environment variable to add the values.
Fix #1168
> Update ephemeral executor with node selector configuration

- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorService.java
- executor/src/main/java/org/terrakube/executor/service/scripts/ScriptEngineService.java
- executor/src/main/java/org/terrakube/executor/service/workspace/SetupWorkspace.java
- executor/src/main/java/org/terrakube/executor/service/workspace/SetupWorkspaceImpl.java
Adding support to use a private extension repository, to use it we just need to add the following environment variable at the organization level.
PRIVATE_EXTENSION_VCS_ID_AUTH
> The above will require the vcs id to use when authentication to the private extension repository
For example when using the helm chart we can set the private extension repository like the following:
```yaml
executor:
properties:
toolsRepository: "https://myprivate.com/secret/my-private-repository.git"
toolsBranch: "main"
```
Fix #928
> Add private extension repository support

- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.22.0-global-var-key-size.xml
Allow to create global variable with a big name like the below example:
Fix #1208
> Change size globalvar/workspace key value

- api/src/main/java/org/terrakube/api/plugin/redirect/RedirectController.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/ScheduleJob.java
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeController.java
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
This will fix the "run-id" logic when running the following command.
```
terraform plan -out myPlan.tfplan
```
Now the file "myPlan.tfplan" will have the correct values, for example:
```
{"remote_plan_format":1,"run_id":"run-116","hostname":"terrakube-api.minikube.net"}
```
And the logs will show the id like "run-XXXX"
Partial fix for the following  #1166 
The `terraform apply myPlan.tfplan` logic still needs to be added when using remote executions
> Fix run id logic for terraform remote plan

- api/src/main/java/org/terrakube/api/plugin/security/authentication/dex/DexWebSecurityAdapter.java
- api/src/main/java/org/terrakube/api/plugin/vcs/WebhookService.java
- api/src/main/java/org/terrakube/api/plugin/vcs/WebhookServiceBase.java
- api/src/main/java/org/terrakube/api/plugin/vcs/provider/bitbucket/BitBucketWebhookService.java
- api/src/main/java/org/terrakube/api/plugin/vcs/provider/github/GitHubWebhookService.java
- api/src/main/java/org/terrakube/api/plugin/vcs/provider/gitlab/GitLabWebhookService.java
- api/src/main/java/org/terrakube/api/repository/WebhookRepository.java
- api/src/main/java/org/terrakube/api/rs/Organization.java
- api/src/main/java/org/terrakube/api/rs/hooks/webhook/WebhookManageHook.java
- api/src/main/java/org/terrakube/api/rs/hooks/webhook/WebhookManagementException.java
- api/src/main/java/org/terrakube/api/rs/hooks/workspace/WorkspaceManageHook.java
- api/src/main/java/org/terrakube/api/rs/webhook/Webhook.java
- api/src/main/java/org/terrakube/api/rs/webhook/WebhookEvent.java
- api/src/main/java/org/terrakube/api/rs/workspace/Workspace.java
- api/src/main/resources/application.properties
- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.22.2-webhook-triggers.xml
- ui/src/domain/Workspaces/Create.jsx
- ui/src/domain/Workspaces/Details.jsx
This change updates the webhook functionality and adds three fields in the UI: branch, path and template so that the webhook can be triggered on a set path, branch and execute the configured template.
1. Replace the deprecated functions/methods in `DexWebSecurityAdapter.java` while `Accept` is added to the allowed header for Elide JSON atomic operations.
2. Replace the deprecated `Where` annotation in `Workspace.java` with the new `SQLRestriction`
This is enhancement to #703
> feat: separate webhook configuration out

- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ephemeral/EphemeralExecutorService.java
Adding options to customize ephemeral executor using the following environment variables.
- EPHEMERAL_CONFIG_NODE_SELECTOR_TAGS
- EPHEMERAL_CONFIG_SERVICE_ACCOUNT
- EPHEMERAL_CONFIG_ANNOTATIONS
> The EPHEMERAL_CONFIG_NODE_SELECTOR_TAGS and EPHEMERAL_CONFIG_ANNOTATIONS allow to have several values separated by a semicolon
For example this can be used at workspace level like the following:
Example:
> Refactor node selector configuration for ephemeral executor

- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeController.java
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
- api/src/main/java/org/terrakube/api/plugin/state/model/workspace/WorkspaceData.java
- api/src/main/java/org/terrakube/api/plugin/state/model/workspace/WorkspaceError.java
- api/src/main/java/org/terrakube/api/plugin/state/model/workspace/WorkspaceModel.java
- api/src/test/java/org/terrakube/api/TfcApiTests.java
This will fix the logic to run a terraform plan using the CLI driven workflow when the workspaces is locked like the following configuration.
Now when running the terraform command it will show the difference like the below:
```shell
user@pop-os:~/git/simple-terraform$ terraform plan
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
+ create
Terraform will perform the following actions:
+ resource "null_resource" "next" {
+ id = (known after apply)
}
+ resource "null_resource" "next2" {
+ id = (known after apply)
}
+ resource "null_resource" "next3" {
+ id = (known after apply)
}
+ resource "null_resource" "next4" {
+ id = (known after apply)
}
+ resource "null_resource" "previous" {
+ id = (known …
```
> fix: Change lock logic for local execution in CLI driven workflow

- api/src/main/java/org/terrakube/api/plugin/json/TofuJsonController.java
- api/src/main/java/org/terrakube/api/plugin/security/authentication/dex/DexWebSecurityAdapter.java
- executor/src/main/resources/application.properties
This change the logic to read the `https://api.github.com/repos/opentofu/opentofu/releases` endpoint, terrakube will only check the releases endpoint every 30 minutes and save the response to REDIS to be reuse the information in other api calls.
Fix #1239
> fix: rate limited by github api

- api/src/main/java/org/terrakube/api/plugin/scheduler/inactive/InactiveJobs.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/inactive/InactiveJobsService.java
- api/src/main/java/org/terrakube/api/repository/JobRepository.java
This will execute and setup a quartz job when the API is starting to correctly cancel jobs that has been running for more that 6 hours, the quartz job to check inactive jobs will be executed every 5 minutes.
The logs will show something like the following:
```shell
2024-09-13T21:47:47.914Z  INFO 1 --- [           main] o.t.a.p.s.inactive.InactiveJobsService   : Setup job to cancelled inactive jobs
2024-09-13T21:47:47.916Z  INFO 1 --- [           main] o.t.a.p.s.inactive.InactiveJobsService   : Create Schedule for inactive jobs: DEFAULT.TerrakubeV2_InactiveJobs_ae638dea-dff2-459f-a9f7-549283fca505
2024-09-13T21:47:47.964Z  INFO 1 --- [           main] o.t.a.p.s.inactive.InactiveJobsService   : jobDetail is null false
2024-09-13T21:47:47.964Z  INFO 1 --- [           main] …
```
> fix: correctly cancel long running jobs

- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
- api/src/main/java/org/terrakube/api/repository/JobRepository.java
- api/src/main/resources/application.properties
This change takes a parameter of the number of executor replicas and uses that as the capacity for the whole Terrakube instance. This could be improved later on if more different types of agents are supported.
fix #1285
> feat: Correct queue and run prompt for CLI

- api/src/main/java/org/terrakube/api/plugin/security/state/StateService.java
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeController.java
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
- api/src/main/java/org/terrakube/api/plugin/storage/controller/TerraformStateController.java
- api/src/main/java/org/terrakube/api/plugin/token/team/TeamTokenController.java
- api/src/main/java/org/terrakube/api/repository/TeamRepository.java
- api/src/main/java/org/terrakube/api/rs/team/Team.java
- api/src/main/java/org/terrakube/api/rs/token/group/Group.java
- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.23.0-team-manage-state.xml
- dynamic-credential-setup/azure/main.tf
- dynamic-credential-setup/gcp/main.tf
- dynamic-credential-setup/gcp/provider.tf
- ui/src/domain/Settings/EditTeam.jsx
- ui/src/domain/Workspaces/Details.jsx
- ui/src/domain/Workspaces/DownloadState.jsx
- ui/src/domain/Workspaces/Schedules.jsx
- ui/src/domain/Workspaces/States.jsx
- ui/src/domain/Workspaces/Tags.jsx
- ui/src/domain/Workspaces/Variables.jsx
This change adds a separate role for managing Terraform state and also disables the corresponding UI items for users who can't mange workspace or state.
1. Users who doesn't have the permission to manage state can run Terraform plan and apply but can't manipulate state with command such as `terraform state rm|pull|push`
fix #1245
> feat: Add manageState permission

- api/src/main/java/org/terrakube/api/plugin/redirect/RedirectController.java
Hello @alfespa17, @jcanizalez;
This PR addresses an issue where the redirect URL for job runs was incorrectly including the 'run-' prefix in the jobId, resulting in an invalid redirect.
For example: 
- The 'run-' prefix is now removed from the jobId when forming the redirect URL.
- The updated URL correctly points to `/organizations/{organizationId}/workspaces/{workspaceId}/runs/{jobId}` without the 'run-' prefix.
This fix ensures that the redirect URL for job runs is properly formed, preventing errors when navigating to specific job run pages.
Could you please review this PR when you're available?
> fix: remove 'run-' prefix from jobId in redirect URL

- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.23.1-team-manage-state-hotfix.xml
This will update the `manageState` value to "false" in `teams` table
Fix #1344
> hotfix:set manageState value to false in existing teams

- ui/src/domain/Workspaces/Details.jsx
Fix #1355 Workspace description
Commit: 44855a0c38cc7d67623b0d581ccbbf64b9404eed
Author: Avinashs7
Date: 01/10/2024
Display workspace description in details section, with option to add a description if none exists
> fix: Add workspace description link is displayed only if description not present for a workspace.

- api/src/main/java/org/terrakube/api/plugin/security/state/StateService.java
- api/src/test/java/org/terrakube/api/WorkspaceTests.java
Fix issue in version 2.23.1 when using `terraform_remote_state` datasource, now the executor component is able to download the state file correctly when using `terraform_remote_state`
Adding test cases to correctly validate if the state can be downloaded by the executor or a normal user.
```
user@pop-os:~/git/simple-terraform/shared-state$ terraform apply
Running apply in HCP Terraform. Output will stream here. Pressing Ctrl-C
will cancel the remote apply if it's still pending. If the apply started it
will stop streaming the logs, but will not stop the apply running remotely.
Preparing the remote apply...
To view this run in a browser, visit:
https://terrakube-api.minikube.net/app/simple/reference-shared/runs/run-5
Waiting for 0 queued run(s) to finish before starting...
Waiting for 0 …
```
> fix: issue when executor is downloading the state file using terraform_remote_state

- api/src/main/java/org/terrakube/api/rs/module/GitTagsCache.java
This PR will fix the issue when the API is connecting to a REDIS with SSL enabled.
```yaml
api:
version: "2.23.2"
defaultRedis: false
env:
- name: TerrakubeRedisSSL
value: "true"
- name: TerrakubeRedisTruststorePath
value: /layers/paketo-buildpacks_bellsoft-liberica/jre/lib/security/cacerts 
- name: TerrakubeRedisTruststorePassword
value: changeit
properties:
redisHostname: "MYREDISHOSTNAME.redis.cache.windows.net"
redisPassword: "mysuperpassword"
```
Logs:
```shell
2024-10-08T21:13:42.610Z  INFO 1 --- [           main] o.t.a.p.s.StreamingConfiguration         : Redis Configuration=> User: username is null, Hostname: MYREDISHOSTNAME.redis.cache.windows.net, Port: 6380, Ssl: true
2024-10-08T21:13:42.618Z  INFO 1 --- [           main] o.t.a.p.s.StreamingConfiguration         : Redis …
```
> fix: REDIS connection using ssl in API

- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
There are repeated output printed out to API log from Terraform apply because of way Terraform cloud handles TCP retransmission. This change solve the issues by move the log line to bottom to remove repeated logs, and also update the log level to debug from info.
> fix: remove excessive apply output from API logs

- api/src/main/java/org/terrakube/api/rs/job/Job.java
- api/src/main/java/org/terrakube/api/rs/workspace/Workspace.java
Allow users without manage workspace permission to trigger runs from UI. This enhances the security posture so that users who uses the workspace don't necessarily have the permission to update any settings of the workspace.
> feat: Allow users w/o manage perm to trigger run

- executor/pom.xml
- executor/src/main/java/org/terrakube/executor/service/terraform/TerraformExecutorServiceImpl.java
This change fixes the display overlaps between error and standard output by redirect error output to standard, in which case Terraform will display the errors at the end of the standard output.
fixes #1394
> fix: error output overlaps with standard output

- executor/src/main/java/org/terrakube/executor/plugin/tfstate/aws/AwsTerraformStateImpl.java
- executor/src/main/java/org/terrakube/executor/plugin/tfstate/aws/AwsTerraformStateProperties.java
- executor/src/main/java/org/terrakube/executor/plugin/tfstate/configuration/TerraformStateAutoConfiguration.java
- executor/src/main/resources/application.properties
This will allow to include or not the terraform backend state keys inside the internal backend override using the environment variable `AwsIncludeBackendKeys`
Fix #1411
> Allow to include or remove terraform backend keys in AWS

- api/src/main/java/org/terrakube/api/rs/module/Module.java
When the module is saved, the ID of GitHubAppToken is not saved, this change fixes it by using the right JPA annotation.
Additional changes;
1. Organize imports
> fix: GitHub App Token not saved for modules

- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
- api/src/main/java/org/terrakube/api/plugin/storage/aws/AwsStorageTypeServiceImpl.java
- executor/pom.xml
- executor/src/main/java/org/terrakube/executor/plugin/tfoutput/aws/AwsTerraformOutputImpl.java
- executor/src/main/java/org/terrakube/executor/plugin/tfoutput/aws/AwsTerraformOutputProperties.java
- executor/src/main/java/org/terrakube/executor/plugin/tfoutput/configuration/TerraformOutputAutoConfiguration.java
- executor/src/main/java/org/terrakube/executor/plugin/tfstate/aws/AwsTerraformStateImpl.java
- executor/src/main/java/org/terrakube/executor/plugin/tfstate/aws/AwsTerraformStateProperties.java
- executor/src/main/java/org/terrakube/executor/plugin/tfstate/configuration/TerraformStateAutoConfiguration.java
- executor/src/main/resources/application.properties
Fix #1204 
- Migrating to AWS SDK version 2
- Allow to use DefaultCredentialsProvider.create() when environment variable "AwsEnableRoleAuth=true"
> feat: Migrate Terrakube Executor to AWS sdk v2

- api/src/main/java/org/terrakube/api/plugin/vcs/WebhookService.java
Hi @alfespa17 !
Following our discussion on this [topic](https://github.com/AzBuilder/terraform-provider-terrakube/issues/83) I'd like to propose a new way to do the matching for the branch list. The idea is as follow
- Be able to say I want to match all branch except these ones
- Keep the previous logic with startsWith branch
The only thing is that I do not automatically return `True` when the branch is the same as the workspace's default branch. I don't know if this is an issue ? 
It's just a proposal for us to be able to achieve our goals ! Lemme know if you approve it :) 
Regards
> feat: enhance branch matching with regex

- api/src/main/java/org/terrakube/api/plugin/scheduler/ScheduleJobService.java
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
People are quite sensitive to the amount of time they have to wait for Terraform runs kicked off from CLI, this change triggers such runs straight after it's created.
1. Format
2. Remove excessive `startNow` call from `createJobContextNow`
> feat: Improve CLI driven workflow execution time

- api/src/main/java/org/terrakube/api/rs/workspace/Workspace.java
- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.24.0-lock-description.xml
- ui/src/domain/Workspaces/Details.jsx
This will allow to set a lock description for a workspace and show a message warning like this:
fix #1358
> feat: Adding lock description warning in workspace details

- ui/src/domain/Workspaces/Details.jsx
This will remove the VCS id relationship from a Worskpace when deleting the resource from the UI
This will allow to remove the VCS connection without the following error once there are no workspaces using the VCS id.
```
Caused by: org.h2.jdbc.JdbcSQLIntegrityConstraintViolationException: Referential integrity constraint violation: "FK_WORKSPACE_VCS: PUBLIC.WORKSPACE FOREIGN KEY(VCS_ID) REFERENCES PUBLIC.VCS(ID) ('16ca2667-cf85-4ffa-85af-fa93dde65b84')"; SQL statement:
delete from vcs where id=? [23503-224]
```
Fix #1100
> fix: Remove VCS client reference when deleting workspace

- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ephemeral/EphemeralExecutorService.java
- ui/src/domain/Workspaces/Create.jsx
- ui/src/domain/Workspaces/Details.jsx
Hey @alfespa17 !
We are currently working on ephemeral agents and we would like to add the ability to mount volumes on the jobs to allow for custom configuration like passing configuration files to interact with cloud providers. Do you think that could be a cool feature ?
Also, following this [PR](https://github.com/AzBuilder/terrakube/pull/1457) I update the message in the Terrakube UI to tell user that they can use regex for branch matching as well !
Regards !
> feat: add possibility to mount config map on ephemeral job agent

- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.24.0-collection-data-constraints.xml
- api/src/main/resources/db/changelog/local/changelog-2.24.0-collection-data.xml
The latest beta release 2.24.0-beta.5 include `changelog-2.24.0-collection-data.xml` that was later modified adding some constraints [here](https://github.com/AzBuilder/terrakube/pull/1529/files), in order to not break liquibase execution I move the database constraints to a new file
> fix: Moving liquibase script constraint to a new file

- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
- api/src/main/java/org/terrakube/api/plugin/token/team/TeamTokenController.java
- api/src/main/java/org/terrakube/api/rs/checks/job/TeamManageJob.java
- api/src/main/java/org/terrakube/api/rs/job/Job.java
- api/src/main/java/org/terrakube/api/rs/team/Team.java
- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.24.0-manage-job.xml
- api/src/test/java/org/terrakube/api/JobTests.java
- api/src/test/java/org/terrakube/api/TfcApiTests.java
- ui/src/domain/Jobs/Create.jsx
- ui/src/domain/Settings/EditTeam.jsx
- ui/src/domain/Settings/Teams.jsx
Adding specific permission to trigger jobs from the UI and CLI
If the user doesnt have the manage job permission the UI will show a little error message now
When running the terraform/tofu cli it will show the message like this:
```shell
user@pop-os:~/git/simple-terraform$ terraform plan
╷
│ Error: Insufficient rights to generate a plan
│ 
│ The provided credentials have insufficient rights to generate a plan. In
│ order to generate plans, at least plan permissions on the workspace are
│ required.
╵
```
> feat: Adding new manage job permission

- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorContext.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorService.java
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/model/Flow.java
- executor/src/main/java/org/terrakube/executor/service/mode/TerraformJob.java
- executor/src/main/java/org/terrakube/executor/service/terraform/TerraformExecutorServiceImpl.java
Hi @alfespa17 !
I'd like to propose this small change and add a new field to the Terrakube template. I change the Flow template in the API and added it to the Executor job. 
However, I'd like your inputs about it, I think I'm missing the part where the data is transmitted from the API that parse the yaml to the Executor that use the content of the Yaml to run the Job. I tried to find it but I couldn't find the connection between the 2 components unfortunately. My guess is that the API set the job in the queue and the executor will pick'em for execute. I'm really not sure that the field `ingore_error` will be available in the Executor context. Could you explain me please ? :) 
Regards
> feat: Allow to continue template execution using "ignoreError" property

- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ephemeral/EphemeralExecutorService.java
This PR support value in the toleration config.
In GCP we can't create tolerations using only key, and in some configurations, we need to support value in the toleration.
Now, terrakube supports only: **key:operator:effect**, the PR insert the possibilily to set: **key=value:operator:effect**.
Thank you
> feat: support value in the tolerations config

- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ephemeral/EphemeralExecutorService.java
Adding missing "value" in toleration to allow the following `key=value:operator:effect`
This will backported the what you added to 2.24.X @klinux
> fix: missing value in the tolerations config (#1592)

- ui/package.json
- ui/src/ActionLoader.jsx
- ui/src/domain/Modules/Create.jsx
- ui/src/domain/Modules/Details.jsx
- ui/src/domain/Modules/List.jsx
- ui/src/domain/Organizations/Details.jsx
- ui/src/domain/Settings/AddVCS.jsx
- ui/src/domain/Settings/VCS.jsx
- ui/src/domain/Workspaces/Create.jsx
- ui/src/domain/Workspaces/Details.jsx
- ui/src/domain/Workspaces/Import.jsx
- ui/yarn.lock
Build image was failing with the following message when using react-icons 5.4.0
`Attempted import error: 'SiAzuredevops' is not exported from 'react-icons/si' (imported as 'SiAzuredevops').`
> fix: Replace SiAzuredevops with VscAzureDevops in react-icons 5.4.0

- ui/src/domain/Workspaces/Variables.jsx
This will show the variables description using a tooltip like the following inside the workspace details.
Fix #1619
> feat: Showing variables description in workspace details

- api/src/main/java/org/terrakube/api/rs/vcs/Vcs.java
- api/src/main/java/org/terrakube/api/rs/workspace/Workspace.java
- ui/src/domain/Settings/VCS.jsx
This will show a message that a VCS provider can't be deleted because there a workspaces that are using it
> This will only work for workspace that were deleted after this was implemented https://github.com/AzBuilder/terrakube/pull/1502 because there could be some deleted workspaces that could have the reference in the database, for previous workspaces it will be required to connect to the database and remove the reference manually
Fix #1666
> feat: Validate workspace relationship when deleting a vcs provider

- ui/src/domain/Jobs/Create.jsx
- ui/src/domain/Workspaces/Details.jsx
Fix #1622 
> When using the CLI driven workflow the branch name is "remote-content" and it should not be changed
> feat: Allow to select branch name when using the UI

- api/pom.xml
- executor/pom.xml
- registry/pom.xml
Hello,
As discussed in #1728, this pull request fix the missing dependency for connecting to S3 bucket using Kubernetes service account.
For some reason I am not able to build main but this was tested on `release/2.24.X`.
> Fix: S3 IAM access through Kubernetes service account

- api/pom.xml
- api/src/main/java/org/terrakube/api/plugin/datasource/DataSourceAutoConfiguration.java
- api/src/main/java/org/terrakube/api/plugin/datasource/DataSourceConfigurationProperties.java
- api/src/main/java/org/terrakube/api/plugin/datasource/DataSourceType.java
- api/src/main/java/org/terrakube/api/plugin/datasource/PostgresAwsIamAuthDataSource.java
- api/src/main/resources/application-demo.properties
- api/src/main/resources/application.properties
Hello, 
For my use case, I need Terrakube to connect to RDS. We have a strict no static password, Terrakube already supports S3 access using AWS DefaultCredentialsProvider but does not have a way to do it for dataSources.
This PR allow connecting to RDS Postgres database using the AWS IAM.
Added:
- A custom implementation of `PGSimpleDataSource.getConnection` that allows pulling and refreshing AWS RDS token
- Two new configs:
- `DatasourceAwsIamAuth` (`boolean`, default: `false`): Enable pulling Postgres password using AWS IAM
- `DatasourceAwsRegion` (`string`, default: `"aws-region-not-set"`): The region of the RDS
- A new dependency on: `software.amazon.awssdk` > `rds`
Test:
- It was tested on AWS RDS Postgres
Let me know if you want me to change things, this is my first java PR
> Feature: AWS IAM auth for POSTGRES dataSource

- api/src/main/java/org/terrakube/api/plugin/vcs/provider/gitlab/GitLabWebhookService.java
This will fix the logic to get the project id when creating a webhook with Gitlab
Example: 
Fix #1583
> fix: Gitlab webhook creation

- .vscode/tasks.json
- ui/src/domain/Organizations/Create.jsx
> fix: validate org name only contains letters and numbers, fix java version in gitpod

- api/pom.xml
- api/src/main/java/org/terrakube/api/plugin/security/authentication/dex/DexWebSecurityAdapter.java
- api/src/main/java/org/terrakube/api/plugin/security/encryption/EncryptionService.java
- api/src/main/java/org/terrakube/api/plugin/security/encryption/InternalEncryptionService.java
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeController.java
- api/src/main/java/org/terrakube/api/plugin/state/RemoteTfeService.java
- api/src/test/java/org/terrakube/api/EncryptionTests.java
- api/src/test/java/org/terrakube/api/ServerApplicationTests.java
Previously when using the CLI driven workflow with remote execution Terrakube return the property `log-read-url` to the terraform/tofu cli using the following paths: 
```
/applies/{jobId}/logs
/plans/{jobId}/logs
``` 
> Terraform/tofu cli uses the path to read the log streaming.
With this change the logic will encrypt the value instead of using just the `jobId`, it will use AES/GCM/NoPadding to encrypt the values from the URL like the following:
```
/applies/logs/-1psjhcp26q6cy47f5z94oj4v6/-7471qtqoo6st1opld4jx58nhh
/applies/logs/-5jxcuqypoixzxh981o8yh8sbr/-3ja54lwjtoec60t9mf4jh94xa
```
The values are encrypted using  the internal token secret
> feat: Improve log-reader-url logic for remote CLI driven workflow

- ui/src/domain/Home/App.js
I have fixed the issue by using the expiry timestamp existing in the user object in localstorage. But I assume it needs to be fixed when it is been rejected in authorization process of each protected route.
Let me know if authorization middleware is done then I can work that as well.
There is an expiry timestamp in the localstorage, change it to nearby time and wait until time crosses and try to request anything in the UI then it will route to login page.
I have tested manually by modifying the expiry time in the localstorage to mimic the real time expiration.
Kindly let me know if any error exists.
Fix #1620
> fix: UI directs to login page when the access token is expired

- registry/pom.xml
Fix #1886
This will remove the dependency commons-text from the registry container.
Adding scope `test` will give the following inside the container
Without `test`scope  will create the container like the following that is including apache commons text 1.9
> fix: wrong dependency scope inside the registry

- api/pom.xml
- api/src/main/java/org/terrakube/api/plugin/datasource/DataSourceAutoConfiguration.java
- api/src/main/java/org/terrakube/api/plugin/datasource/DataSourceType.java
MYSQL 8.0  looks like is no longer working and it has not been tested in a long time and maybe it will require several code changes that could impact postgresql and mssql
fix #1909
> fix: Remove mysql code

- api/src/main/resources/db/changelog/local/changelog-2.25.1-webhook-events.xml
- api/src/main/resources/db/changelog/local/changelog-2.25.1-webhook-tidyup.xml
- pom.xml
For some reason liquibase scripts did run correctly in postgresql but not in sql azure, this PR update the script to fix the issue.
Changing the scripts update the md5sum inside the table `DATABASECHANGELOG` that is manage by liquibase, that will require to execute the following manually:
```shell
UPDATE DATABASECHANGELOG SET MD5SUM='9:a3d5f8c336d36a036e7c150abea93732' WHERE ID='2-25-1-1';
UPDATE DATABASECHANGELOG SET MD5SUM='9:3a462f1637e96c42cf298f2e74ffc934' WHERE ID='2-25-1-21';
```
> The above will only impact user using postgresql that deployed version 2.26.0-beta.2 or 2.26.0-beta.3
I tried adding a new script to fix/change the values automatically but it is not possible
```xml
<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog …
```
> fix: Update liquibase scripts to fix issue when running in SQL Azure

- ui/src/domain/Home/App.tsx
Hello @alfespa17, @jcanizalez,
This pull request updates the footer to dynamically display the current year instead of using a hardcoded value.
The change replaces the static year 2025 with {new Date().getFullYear()}, ensuring the footer is always up-to-date.
Let me know if there's anything else you'd like me to improve.
> fix: Make footer year dynamic by using new Date().getFullYear() instead of static year

- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ephemeral/EphemeralExecutorService.java
Hi @alfespa17 !
I'd like to propose this small change for ephemeral agents. The idea is that we use a Persistent volume claim (PVC) that we mount on our jobs at each run. Then since `TF_PLUGIN_CACHE_DIR` is set, tofu "automatically" comes to grab the content of this folder in case the provider was previously downloaded. 
NB: PVC must be defined in the Terrakube Helm charts. Terrakube app should not be responsible for PVC provisionning.
Lemme know your thoughts
PS: not tested
> feat: mount pvc on jobs

- ui/conf/conf.d/bitnami.conf
Currently, the UI only listens to IPv4. I'm running an IPv6 only cluster and was unable to run the UI unless I override the conf with a volume mount with proposed changes.
> fix: Add listen for IPv6 for terrakube UI

- api/src/main/java/org/terrakube/api/plugin/vcs/WebhookResult.java
- api/src/main/java/org/terrakube/api/plugin/vcs/WebhookService.java
- api/src/main/java/org/terrakube/api/plugin/vcs/provider/github/GitHubWebhookService.java
- api/src/main/java/org/terrakube/api/rs/webhook/WebhookEventType.java
- ui/src/domain/Workspaces/Settings/Webhook.tsx
This PR is adding support to trigger a job in Terrakube when a Github Release is created.
Example:
The webhooks setup is using a regex like `release/v.*`
It will trigger something similar inside the logs
```
2025-05-06T15:58:26.485Z  INFO 17946 --- [nio-8080-exec-8] o.t.api.plugin.vcs.WebhookServiceBase    : WorkspaceId: 777be819-c32b-4eb6-906d-1432b2862e4c
2025-05-06T15:58:26.485Z  INFO 17946 --- [nio-8080-exec-8] o.t.api.plugin.vcs.WebhookServiceBase    : verify signature for Github webhook
2025-05-06T15:58:26.485Z  INFO 17946 --- [nio-8080-exec-8] o.t.api.plugin.vcs.WebhookServiceBase    : Parsing Github webhook payload
2025-05-06T15:58:26.486Z  INFO 17946 --- [nio-8080-exec-8] o.t.a.p.v.p.github.GitHubWebhookService  : Received release created webhook event for repository …
```
> feat: Support to trigger a job when creating releases in Github

- api/src/main/java/org/terrakube/api/plugin/migrate/MigrateController.java
- api/src/main/java/org/terrakube/api/plugin/migrate/MigrateService.java
- api/src/main/java/org/terrakube/api/plugin/storage/StorageTypeService.java
- api/src/main/java/org/terrakube/api/plugin/storage/aws/AwsStorageTypeServiceImpl.java
- api/src/main/java/org/terrakube/api/plugin/storage/azure/AzureStorageTypeServiceImpl.java
- api/src/main/java/org/terrakube/api/plugin/storage/gcp/GcpStorageTypeServiceImpl.java
- api/src/main/java/org/terrakube/api/plugin/storage/local/LocalStorageTypeServiceImpl.java
- api/src/main/java/org/terrakube/api/rs/workspace/history/History.java
- api/src/main/java/org/terrakube/api/rs/workspace/history/archive/Archive.java
- scripts/template/minio/docker-compose.yaml
This will allow to move a workspace to a different organization doing the following request
```
curl --location --request POST 'https://terrakube-api.minikube.net/migrate/v1/workspace/5ed411ca-7ab8-4d2f-b591-02d0d5788afc/moveTo/3a130a1c-d96f-4f99-83b8-58d472567e3a' --header 'Content-Type: application/json' --header 'Authorization: Bearer XXXXXXX'
```
Fix #2085
> feat: Adding support to migrate a workspace to a different organization

- ui/src/modules/layout/PageWrapper/PageWrapper.tsx
Hello @alfespa17, @jcanizalez,
Previously, PageWrapper would render both the loading spinner and the page content (`children`) at the same time. This caused components like empty tables or uninitialized UI elements to appear prematurely while data was still being fetched.
This update changes the logic so that children are only rendered after `loading` is false. While loading, only the spinner and optional `loadingText` are shown. This improves perceived performance and avoids UI flickering or confusion during API requests.
Also simplifies usage by allowing consumers to rely fully on the `loading` prop without wrapping content in custom `isLoading ? ... : ...` checks.
> fix: hide PageWrapper children while loading is true

- .devcontainer/.env
- .devcontainer/Dockerfile
- .devcontainer/README.md
- .devcontainer/config-ldap.ldif
- .devcontainer/config-ldap.yaml
- .devcontainer/devcontainer.json
- .devcontainer/docker-compose.yml
- .devcontainer/env-config.js
- .devcontainer/traefik_dynamic.yml
- .devcontainer/type
- .gitignore
- .vscode/extensions.json
- .vscode/settings.json
- .vscode/tasks.json
- README.md
- docker-compose/README.md
- scripts/setupDevelopmentEnvironment.sh
- ui/vite.config.mts
This will allow to develop Terrakube using devcontainers with vscode  instead of using gitpod
For more details check the following:
`.devcontainers/README.MD`
> The below was tested using ubuntu-based distribution, not sure if it will require changes to run in macos, windows or codespaces
It will allow to easily test or modify all the components
It will also allow to use https to test all the terraform cli features like for example the registry support
It will allow to run terraform login from inside the container
>  feat: Adding vscode devcontainer support

- api/src/main/java/org/terrakube/api/rs/webhook/WebhookEvent.java
- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.26.1-webhook-data-fix.xml
* fix: Set webhook priority to 0 for old workspaces
> fix: Set webhook priority to 0 for old workspaces (#2185)

- api/src/main/java/org/terrakube/api/plugin/token/dynamic/JwksController.java
This is related to this comment https://github.com/openbao/openbao/issues/1475#issuecomment-3001504664
Before the change there is a "=" at the end of property "n"
```json
{
"keys": [
{
"kty": "RSA",
"use": "sig",
"n": "APOXbjzPkcpGrh2oLKVyV91FoLsa94TVMoZXEN2cgNvAe3_A1_hRgDBblLU_DUTSu3Douhds-23CakRQgE6PMPl9DveQ086wJxQJ1zXKKRHZIKIguXxRHJb8-8J3Eh-UN1NIUiq6azSa4yoc8b2nRLCJ-LzSNMWvzxzeOfDFORdVSjNO53IGG7XaJ8A3kne2S7WlNzFxCRHWz4NFzVcrfwwGkL7qIhl6lnpikNClLMYw54ztfae5CO1Xj0o4Jgf5zUCClwSlZrk-VQw32ivZWQpmpwMRvCTl1y9Eqr8bkBrf31JkgWH-WhngJ7h1RtKV0FHHswBR_Edq4oSxZZRa28s=",
"e": "AQAB",
"kid": "03446895-220d-47e1-9564-4eeaa3691b42",
"alg": "RS256"
}
]
}
```
After the change the "=" is no longer included
```json
{
"keys": [
{
"kty": "RSA",
"use": "sig",
"n": …
```
> fix: Remove padding from jwks endpoint

- .devcontainer/Dockerfile
- .devcontainer/docker-compose.yml
- api/src/main/java/org/terrakube/api/plugin/scheduler/job/tcl/executor/ExecutorService.java
- api/src/main/java/org/terrakube/api/plugin/token/dynamic/DynamicCredentialsService.java
- scripts/setupDevelopmentEnvironment.sh
- terrakube-policy.hcl
- vault-jwt-auth-role.json
- vault/README.md
- vault/backend.tf
- vault/main.tf
This PR add support to read values from Openbao/Vault using dynamic credentials to authenticate
Example:
Running openbao in development mode
```shell
bao server -dev -dev-root-token-id="dev-only-token" 
```
Use the following openbao policy 
```terraform
path "auth/token/lookup-self" {
capabilities = ["read"]
}
path "auth/token/renew-self" {
capabilities = ["update"]
}
path "auth/token/revoke-self" {
capabilities = ["update"]
}
path "shared/data/kv/creds" {
capabilities = ["read"]
}
```
JWT Role
```json
{
"policies": ["tfc-policy"],
"role_type": "jwt",
"bound_audiences": ["vault.workload.identity"],
"bound_claims_type": "glob",
"user_claim": "terrakube_workspace_name",
"bound_claims": {
"sub":"organization:simple:workspace:vault"
},
"token_ttl": "20m"
}
```
Adding test values, policy and …
> feat: Openbao/Vault dynamic credentials support

- api/src/main/java/org/terrakube/api/plugin/security/authentication/dex/DexWebSecurityAdapter.java
- registry/src/main/java/org/terrakube/registry/configuration/authentication/dex/DexWebSecurityAdapter.java
This will fix the issue when running the `terraform login ` command with an expired token inside the `credentials.tfrc.json`
Fix #903
> fix: terraform login protocol authentication with expired token

- api/pom.xml
- executor/pom.xml
- registry/pom.xml
This PR fixes the issue when using ssh workspace or modules after upgrading jgit to `7.2.1.202505142326-r`
https://github.com/terrakube-io/terrakube/pull/2191
I guess this is related to https://github.com/terrakube-io/terrakube/issues/2225 but I am not really sure 
```shell
Caused by: java.security.NoSuchAlgorithmException: Unsupported key type (ssh-ed25519) in /home/cnb/.terraform-spring-boot/ssh/registry/f655cc2b-0293-4847-8703-f22fc23bb36d/id_ed25519
2025-07-01T21:24:16.589038508Z 	at org.apache.sshd.common.config.keys.loader.openssh.OpenSSHKeyPairResourceParser.readPublicKey(OpenSSHKeyPairResourceParser.java:221) ~[sshd-osgi-2.15.0.jar:2.15.0]
2025-07-01T21:24:16.589041694Z 	at org.apache.sshd.common.config.keys.loader.openssh.OpenSSHKeyPairResourceParser.extractKeyPairs(OpenSSHKeyPair …
```
> fix: Add Bouncy Castle dependency in API, Executor, and Registry modules

- api/src/main/java/io/terrakube/api/plugin/vcs/WebhookServiceBase.java
- api/src/main/java/io/terrakube/api/plugin/vcs/provider/gitlab/GitLabWebhookService.java
- api/src/test/java/io/terrakube/api/VcsTests.java
This PR is fixing the issue when Terrakube is trying to create the repository webhook because it was not searching the id in a correct way
Fix #1885, Fix #1983
> fix: gitlab webhooks for projects and subgroups

- api/pom.xml
- api/src/test/java/io/terrakube/api/CollectionTests.java
- api/src/test/java/io/terrakube/api/JobTests.java
- api/src/test/java/io/terrakube/api/ServerApplicationTests.java
- api/src/test/java/io/terrakube/api/VcsTests.java
- api/src/test/resources/application-test.properties
- registry/pom.xml
- registry/src/test/java/io/terrakube/registry/ModuleTests.java
- registry/src/test/java/io/terrakube/registry/OpenRegistryApplicationTests.java
- registry/src/test/java/io/terrakube/registry/ProviderTests.java
Terrakube was originally using mockserver but that project is abandon, this PR migrate the tests to use Wiremock
> feat: Migrate test to Wiremock

- api/src/main/java/io/terrakube/api/plugin/json/TerraformJsonController.java
- api/src/test/java/io/terrakube/api/IndexTests.java
- api/src/test/resources/application-test.properties
Implement web client for fetching terraform/tofu index, `IOUtils.toString` was not managing the proxy settings correctly from the below code:
https://github.com/terrakube-io/terrakube/blob/14c33621bf9fc171c36b04e1ef2c5b3e291b45b1/api/src/main/java/io/terrakube/api/plugin/json/TerraformJsonController.java#L29C30-L29C46
fix #2276
> feat: Implement web client for fetching terraform/tofu index

- api/src/main/java/io/terrakube/api/plugin/vcs/WebhookService.java
- api/src/main/java/io/terrakube/api/plugin/vcs/provider/gitlab/GitLabWebhookService.java
- api/src/main/java/io/terrakube/api/plugin/vcs/provider/gitlab/GitlabMergeRequestModel.java
This PR will allow to trigger a job when a merge request is created in Gitlab
Example configuration:
It also fix some logic to delete the webhook from gitlab that was not executed correctly, this is related to https://github.com/terrakube-io/terrakube/issues/2300#issuecomment-3063006873
Merge request will look like this 
This is related also to this issue
https://github.com/terrakube-io/terrakube/issues/396
> feat: Support merge_request event in gitlab

- executor/src/main/java/io/terrakube/executor/service/terraform/TerraformExecutorServiceImpl.java
- executor/src/main/resources/application.properties
- Introduced `enableColorOutput` flag with Spring @Value injection to toggle colored Terraform log output.
- Updated log formatting logic to respect the new `enableColorOutput` setting.
- Modified default configuration in `application.properties` to support dynamic environment-based values.
Example:
fix #2319
> feat: Add configurable color output toggle for Terraform logs

- api/src/main/java/io/terrakube/api/plugin/vcs/provider/gitlab/GitLabWebhookService.java
- api/src/main/java/io/terrakube/api/plugin/vcs/provider/gitlab/GitlabReleaseModel.java
This will allow to use releases events to trigger jobs like the following
Creating release like this in gitlab
> To correctly trigger the job, make sure the release name and tag matches
> feat: Support gitlab releases event to trigger jobs

- api/src/main/java/io/terrakube/api/plugin/vcs/WebhookService.java
- api/src/main/java/io/terrakube/api/plugin/vcs/provider/bitbucket/BitBucketWebhookService.java
- api/src/test/java/io/terrakube/api/ServerApplicationTests.java
- api/src/test/java/io/terrakube/api/VcsTests.java
This pull request is addgin support for different bitbucket events, pull request, push and tag creation (this one is managed as a release event in terrakube)
Example:
> Pull request are triggered for any branch different from main using regex` ^(?!.*main).*$`
Related to #396
> feat: Bitbucket support for push, pull request and tag creation events

- api/src/main/java/io/terrakube/api/rs/module/ModuleVersion.java
- api/src/main/resources/db/changelog/local/changelog-2.27.1-module-versions.xml
Related to #2324 , "commit" is a reserved work for mssql
> fix: changing column name commit is reserved word in mssql

- registry/src/main/java/io/terrakube/registry/service/git/GitServiceImpl.java
- registry/src/main/java/io/terrakube/registry/service/module/ModuleServiceImpl.java
- Enhanced logging in `ModuleServiceImpl` to debug version lists.
- Improved logging in `GitServiceImpl` to trace tag existence checks and repository tags.
To enable logs this environment variable should be added for the registry component 
```env
JAVA_TOOL_OPTIONS="-Dlogging.level.io.terrakube.registry.service.module=DEBUG -Dlogging.level.io.terrakube.registry.service.git=DEBUG"
```
The logs will look like this:
```shell
2025-07-31T22:36:28.723Z  INFO 12616 --- [nio-8075-exec-1] i.t.r.service.module.ModuleServiceImpl   : Search Organization: aws 3a130a1c-d96f-4f99-83b8-58d472567e3a
2025-07-31T22:36:28.723Z  INFO 12616 --- [nio-8075-exec-1] i.t.r.service.module.ModuleServiceImpl   : Search Module iam/aws in Organization aws
2025-07-31T22:36:28.790Z DEBUG 12616 --- [nio-8075-exec-1] …
```
> feat: Add detailed debug and info logging for module and git services

- api/src/main/java/io/terrakube/api/rs/module/Module.java
The transaction phase in the module entity is missing,
https://github.com/terrakube-io/terrakube/blob/5aa94ae198ed5df596c6570def8f57e4ac7be690/api/src/main/java/io/terrakube/api/rs/module/Module.java#L46
The correct way should be 
```
@LifeCycleHookBinding(operation = LifeCycleHookBinding.Operation.CREATE, phase = LifeCycleHookBinding.TransactionPhase.POSTCOMMIT, hook = ModuleManageHook.class)
```
Adding the above generate the following logs and correctly create the job to refresh modules:
```shell
2025-08-01T01:20:40.509Z  INFO 20023 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 8080 (http) with context path '/'
2025-08-01T01:20:40.909Z  INFO 20023 --- [           main] io.terrakube.api.ServerApplication       : Started ServerApplication in 28.25 …
```
> fix: postcommit transaction phase when creating new modules

- api/src/main/java/io/terrakube/api/rs/hooks/module/ModuleManageHook.java
- api/src/main/java/io/terrakube/api/rs/module/Module.java
- api/src/test/java/io/terrakube/api/ModuleTests.java
- api/src/test/java/io/terrakube/api/ServerApplicationTests.java
- Introduced `PRECOMMIT` phase lifecycle hook for module creation.
- Improved logging in `ModuleManageHook` to include module details during lifecycle operations.
- Added assertions and job validation in module creation tests to ensure refresh tasks are scheduled correctly.
The test case is showing the PRECOMMIT and POSTCOMMIT logic
Command to run test
```shell
cd api
mvn test -Dtest=ModuleTests#createModuleAsOrgMember
```
Example
```shell
2025-08-01T08:27:14.758-06:00  INFO 14058 --- [           main] i.t.api.plugin.token.pat.PatService      : Generated Pat c157824f-4363-42ae-95e6-6f733e84f65f
2025-08-01T08:27:14.758-06:00  INFO 14058 --- [           main] i.t.api.plugin.token.pat.PatService      : Pat will expire
2025-08-01T08:27:15.272-06:00  INFO 14058 --- [           main] …
```
> fix: Add precommit lifecycle hook for module creation and enhance logging

- api/src/main/java/io/terrakube/api/rs/module/Module.java
Modules that are not using semantic versioning are breaking the modules page
Example
https://github.com/mongodb/terraform-provider-mongodbatlas.git
Without the above this will be show in the logs:
```shell
terrakube-api-554d59c8b8-d8tbw terrakube-api java.lang.reflect.InvocationTargetException: null
terrakube-api-554d59c8b8-d8tbw terrakube-api    at jdk.internal.reflect.GeneratedMethodAccessor173.invoke(Unknown Source) ~[na:na]
terrakube-api-554d59c8b8-d8tbw terrakube-api    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:na]
terrakube-api-554d59c8b8-d8tbw terrakube-api    at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[na:na]
terrakube-api-554d59c8b8-d8tbw terrakube-api    at …
```
> fix: Validate module not using semantic versioning

- api/src/main/java/io/terrakube/api/plugin/token/dynamic/DynamicCredentialsService.java
- api/src/main/java/io/terrakube/api/plugin/token/dynamic/OpenIdConfigurationController.java
- api/src/main/resources/application-demo.properties
- api/src/main/resources/application.properties
Allows to override the hostname for the dynamic credentials jwt token, this will allow to expose the openid configuration in a different endpoint when using a private cluster.
Example:
> feat: add support for dynamic credentials hostname override

- api/src/main/java/io/terrakube/api/plugin/security/authentication/dex/DexAuthenticationManagerResolver.java
- api/src/main/java/io/terrakube/api/plugin/state/RemoteTfeController.java
- api/src/main/java/io/terrakube/api/plugin/state/RemoteTfeService.java
- api/src/main/java/io/terrakube/api/plugin/state/model/project/OrganizationModel.java
- api/src/main/java/io/terrakube/api/plugin/state/model/project/ProjectData.java
- api/src/main/java/io/terrakube/api/plugin/state/model/project/ProjectList.java
- api/src/main/java/io/terrakube/api/plugin/state/model/project/ProjectModel.java
- api/src/main/java/io/terrakube/api/plugin/state/model/project/Relationships.java
- api/src/main/java/io/terrakube/api/plugin/state/model/workspace/CurrentRunRelationship.java
- api/src/main/java/io/terrakube/api/plugin/state/model/workspace/ProjectRelationship.java
- api/src/main/java/io/terrakube/api/plugin/state/model/workspace/Relationships.java
- api/src/main/java/io/terrakube/api/plugin/token/team/TeamTokenController.java
- api/src/main/java/io/terrakube/api/repository/ProjectRepository.java
- api/src/main/java/io/terrakube/api/rs/Organization.java
- api/src/main/java/io/terrakube/api/rs/checks/project/TeamManageProject.java
- api/src/main/java/io/terrakube/api/rs/checks/project/TeamViewProject.java
- api/src/main/java/io/terrakube/api/rs/project/Project.java
- api/src/main/java/io/terrakube/api/rs/workspace/Workspace.java
- api/src/main/resources/db/changelog/changelog.xml
- api/src/main/resources/db/changelog/local/changelog-2.28.0-project-support.xml
- api/src/test/java/io/terrakube/api/ProjectTests.java
- api/src/test/java/io/terrakube/api/ServerApplicationTests.java
This will allow to run the following when using the CLI driven workflow
```terraform
terraform {
cloud {
hostname = "terrakube-api.platform.local"
workspaces {
name = "test3"
project = "newproject"
}
}
}
```
This PR also added support for this endpoints that are required by the terraform/tofu CLI when using the CLI driven workflow
```
GET /organizations/{organizationName}/projects
POST /organizations/{organizationName}/projects
```
This feature was tested using terraform 1.13.3
> feat: Adding project support

- executor/src/main/java/io/terrakube/executor/service/scripts/bash/BashEngine.java
- executor/src/main/java/io/terrakube/executor/service/terraform/TerraformExecutorServiceImpl.java
For example when using template like this:
```
flow:
- type: "terraformPlan"
step: 100
commands:
- runtime: "BASH"
priority: 100
before: true
script: |
echo "Before terraform/tofu operation"
echo "TF_VAR_HELLO_WORLD=HelloWorld" >> $terrakubeEnv
- runtime: "BASH"
priority: 200
before: true
script: |
echo "$TF_VAR_HELLO_WORLD"
```
Environment variables will be also available when using terraform/tofu operations
fix #2548
> feat: Allow to save environment variables when using bash scripts
